Repository disorderedmaterials/dissolve, pull requests merged in 2021-06, with the labels that each got.

#703 Molecule Energy Optimisation 2
  benchmark/benchmark_files/hexane5k.txt
  benchmark/energy/energy_benchmark.cpp
  src/classes/atom.cpp
  src/classes/atom.h
  src/classes/cell.cpp
  src/classes/cell.h
  src/classes/changedata.cpp
  src/classes/changedata.h
  src/classes/changestore.cpp
  src/classes/changestore.h
  src/classes/configuration.h
  src/classes/configuration_upkeep.cpp
  src/classes/energykernel.cpp
  src/classes/forcekernel.cpp
  src/modules/atomshake/process.cpp
  src/modules/energy/process.cpp
  src/modules/forces/process.cpp
  src/procedure/nodes/collect3d.cpp
Labels: 4

#711 Move Geometry and SystemTemplate out of ListItem
  src/base/geometry.cpp
  src/base/geometry.h
  src/gui/gui.h
  src/gui/gui_funcs.cpp
  src/gui/selectsystemtemplatedialog.h
  src/gui/selectsystemtemplatedialog_funcs.cpp
  src/gui/systemtemplate.h
  src/keywords/geometrylist.cpp
  src/keywords/geometrylist.h
  src/modules/checks/checks.h
  src/modules/checks/init.cpp
  src/modules/checks/process.cpp
Labels: 1

#716 Bugfix 04/06/21 Various
  .gitignore
  src/io/import/data1d.cpp
  src/math/filters.cpp
  src/modules/energy/process.cpp
  src/modules/epsr/process.cpp
  src/modules/neutronsq/init.cpp
  src/modules/neutronsq/process.cpp
  src/modules/xraysq/init.cpp
  src/modules/xraysq/process.cpp
  tests/epsr/water-neutron-xray.txt
  web/content/docs/modules/correlation/neutronsq/_index.md
  web/content/docs/modules/correlation/xraysq/_index.md
  web/content/docs/reference/fileandformat/data1dformat.md
Labels: 2

#708 Fixup AvgMol Module
  .azure-pipelines/templates/system-tests.yml
  src/classes/CMakeLists.txt
  src/classes/species_atomic.cpp
  src/classes/valuestore.cpp
  src/classes/valuestore.h
  src/genericitems/deserialisers.cpp
  src/genericitems/producers.cpp
  src/genericitems/producers.h
  src/genericitems/searchers.cpp
  src/genericitems/serialisers.cpp
  src/io/fileandformat.cpp
  src/io/import/CMakeLists.txt
  src/io/import/values.cpp
  src/io/import/values.h
  src/keywords/CMakeLists.txt
  src/keywords/base.cpp
  src/keywords/base.h
  src/keywords/types.h
  src/keywords/valuestore.cpp
  src/keywords/valuestore.h
  src/math/error.cpp
  src/math/error.h
  src/modules/calculate_avgmol/avgmol.h
  src/modules/calculate_avgmol/functions.cpp
  src/modules/calculate_avgmol/gui/modulewidget_funcs.cpp
  src/modules/calculate_avgmol/process.cpp
  src/modules/datatest/datatest.h
  src/modules/datatest/init.cpp
  src/modules/datatest/process.cpp
  tests/calculate_avgmol/CMakeLists.txt
  tests/calculate_avgmol/README
  tests/calculate_avgmol/bendy.124.restart
  tests/calculate_avgmol/bendy.txt
  tests/calculate_avgmol/bendy.xyz
  tests/calculate_avgmol/water.txt
Labels: 4

#719 Remove ListItem base from Configuration
  src/classes/configuration.cpp
  src/classes/configuration.h
  src/classes/coredata.cpp
  src/classes/coredata.h
  src/gui/getconfigurationnamedialog_funcs.cpp
  src/gui/keywordwidgets/configurationreflist_funcs.cpp
  src/gui/maintabswidget_funcs.cpp
  src/gui/modulelisteditor_funcs.cpp
  src/gui/selectconfigurationdialog.h
  src/gui/selectconfigurationdialog_funcs.cpp
  src/gui/selectconfigurationwidget.h
  src/gui/selectconfigurationwidget_funcs.cpp
  src/keywords/atomtypeselection.cpp
  src/keywords/atomtypeselection.h
  src/keywords/configurationreflist.cpp
  src/keywords/configurationreflist.h
  src/main/comms.cpp
  src/main/configurations.cpp
  src/main/dissolve.h
  src/main/io.cpp
  src/main/objects.cpp
  src/main/simulation.cpp
  src/module/module.cpp
  src/module/module.h
  src/modules/analyse/process.cpp
  src/modules/atomshake/process.cpp
  src/modules/benchmark/process.cpp
  src/modules/bragg/process.cpp
  src/modules/calculate_angle/gui/modulewidget_funcs.cpp
  src/modules/calculate_angle/process.cpp
  src/modules/calculate_avgmol/process.cpp
  src/modules/calculate_axisangle/process.cpp
  src/modules/calculate_dangle/process.cpp
  src/modules/calculate_rdf/process.cpp
  src/modules/calculate_sdf/gui/modulewidget_funcs.cpp
  src/modules/calculate_sdf/process.cpp
  src/modules/checks/process.cpp
  src/modules/energy/energy.h
  src/modules/energy/functions.cpp
  src/modules/energy/process.cpp
  src/modules/epsr/process.cpp
  src/modules/export_coordinates/process.cpp
  src/modules/export_trajectory/process.cpp
  src/modules/forces/process.cpp
  src/modules/geomopt/process.cpp
  src/modules/import_trajectory/process.cpp
  src/modules/intrashake/process.cpp
  src/modules/md/process.cpp
  src/modules/molshake/process.cpp
  src/modules/rdf/gui/modulewidget_funcs.cpp
  src/modules/rdf/process.cpp
  src/modules/skeleton/process.cpp
  src/modules/test/process.cpp
Labels: 2

#720 Remove ListItem base from SiteReference
  src/classes/sitereference.cpp
  src/classes/sitereference.h
Labels: 1

#717 Remove ListItem dependency from SiteStack
  src/classes/configuration.h
  src/classes/configuration_sites.cpp
  src/classes/sitestack.cpp
  src/classes/sitestack.h
  src/procedure/nodes/select.cpp
Labels: 2

#709 System Test Definitions
  tests/CMakeLists.txt
  tests/accumulate/CMakeLists.txt
  tests/atomshake/CMakeLists.txt
  tests/bragg/CMakeLists.txt
  tests/broadening/CMakeLists.txt
  tests/calculate_avgmol/CMakeLists.txt
  tests/calculate_cn/CMakeLists.txt
  tests/calculate_dangle/CMakeLists.txt
  tests/calculate_rdf/CMakeLists.txt
  tests/calculate_rdf/rdf.73.restart.test
  tests/calculate_sdf/CMakeLists.txt
  tests/correlations/CMakeLists.txt
  tests/energyforce1/CMakeLists.txt
  tests/energyforce2/CMakeLists.txt
  tests/energyforce3/CMakeLists.txt
  tests/energyforce4/CMakeLists.txt
  tests/epsr/CMakeLists.txt
  tests/exchangeable/CMakeLists.txt
  tests/ff/CMakeLists.txt
  tests/md/CMakeLists.txt
  tests/molshake/CMakeLists.txt
  tests/rdfmethod/CMakeLists.txt
  tests/restart/CMakeLists.txt
  tests/xray/CMakeLists.txt
Labels: 1

#718 Tidy Cells
  .azure-pipelines/pr.yml
  .azure-pipelines/release.yml
  CMakeLists.txt
  benchmark/energy/energy_benchmark.cpp
  src/classes/cellarray.cpp
  src/classes/cellarray.h
  src/classes/cellneighbour.h
  src/classes/energykernel.cpp
  src/classes/energykernel.h
  src/classes/forcekernel.h
  src/classes/pairpotential.cpp
  src/classes/pairpotential.h
  src/gui/render/axes.cpp
  src/modules/atomshake/process.cpp
  src/templates/vector3.h
  tests/_data/dlpoly/solvated_atom/solvated-argon-rcut5.CONFIG
  tests/_data/dlpoly/solvated_atom/solvated-argon-rcut5.CONTROL
  tests/_data/dlpoly/solvated_atom/solvated-argon-rcut5.FIELD
  tests/_data/dlpoly/solvated_atom/solvated-argon-rcut5.OUT
  tests/_data/dlpoly/solvated_atom/solvated-argon-rcut7.CONFIG
  tests/_data/dlpoly/solvated_atom/solvated-argon-rcut7.CONTROL
  tests/_data/dlpoly/solvated_atom/solvated-argon-rcut7.FIELD
  tests/_data/dlpoly/solvated_atom/solvated-argon-rcut7.OUT
  tests/_data/dlpoly/solvated_atom/solvated-argon-rcut9.CONFIG
  tests/_data/dlpoly/solvated_atom/solvated-argon-rcut9.CONTROL
  tests/_data/dlpoly/solvated_atom/solvated-argon-rcut9.FIELD
  tests/_data/dlpoly/solvated_atom/solvated-argon-rcut9.OUT
  unit/test_cells.cpp
  web/content/docs/startingout/compilation.md
Labels: 4

#724 Bugfix 16/06/21 Various 2
  src/classes/species.h
  src/classes/species_intra.cpp
  src/gui/forcefieldtab_funcs.cpp
  src/gui/maintabswidget_funcs.cpp
  src/main/species.cpp
Labels: 1

#722 Bugfix 16/06/21 Various
  src/classes/braggreflection.cpp
  src/classes/energykernel.cpp
  src/classes/partialset.cpp
  src/gui/models/masterTermModel.cpp
  src/modules/calculate_avgmol/functions.cpp
  src/modules/energy/process.cpp
  src/modules/md/process.cpp
Labels: 2

#731 Unused AtomTypes
  src/main/simulation.cpp
Labels: 1

#729 Restructure and tidy CI
  .azure-pipelines/continuous.yml
  .azure-pipelines/pr.yml
  .azure-pipelines/release.yml
  .azure-pipelines/templates/build-linux-mpi.yml
  .azure-pipelines/templates/build-linux.yml
  .azure-pipelines/templates/build-osx.yml
  .azure-pipelines/templates/build-windows.yml
  .azure-pipelines/templates/package-linux.yml
  .azure-pipelines/templates/package-osx.yml
  .azure-pipelines/templates/package-windows.yml
  .azure-pipelines/templates/tests.yml
Labels: 2
