Repository disorderedmaterials/dissolve, pull requests merged in 2021-11, with the labels that each got.

#835 AtomType Model Upgrade
  src/classes/atomtypemix.cpp
  src/classes/atomtypemix.h
  src/classes/neutronweights.cpp
  src/classes/neutronweights.h
  src/gui/importspeciesdialog_funcs.cpp
  src/gui/keywordwidgets/atomtypevector_funcs.cpp
  src/gui/models/CMakeLists.txt
  src/gui/models/atomTypeFilterProxy.cpp
  src/gui/models/atomTypeFilterProxy.h
  src/gui/models/atomTypeModel.cpp
  src/gui/models/atomTypeModel.h
  src/keywords/atomtypevector.cpp
  src/keywords/atomtypevector.h
  src/modules/neutronsq/process.cpp
  src/procedure/nodes/dynamicsite.cpp
  src/procedure/nodes/dynamicsite.h
  unit/classes/neutronweights.cpp
Labels: 1

#837 Remove list dependency from ChartBlock and ChartHotSpot
  src/gui/charts/chart.hui
  src/gui/charts/chart_funcs.cpp
  src/gui/charts/chartblock.cpp
  src/gui/charts/chartblock.h
  src/gui/charts/charthotspot.cpp
  src/gui/charts/charthotspot.h
  src/gui/charts/modulelist.cpp
  src/gui/charts/procedure.cpp
Labels: 1

#838 AtomType Selection Dialog
  src/classes/species.h
  src/classes/species_atomic.cpp
  src/gui/CMakeLists.txt
  src/gui/selectatomtypedialog.h
  src/gui/selectatomtypedialog.ui
  src/gui/selectatomtypedialog_funcs.cpp
  src/gui/selectatomtypewidget.h
  src/gui/selectatomtypewidget.ui
  src/gui/selectatomtypewidget_funcs.cpp
Labels: 2

#840 Species Term Assignment
  src/classes/empiricalformula.cpp
  src/classes/empiricalformula.h
  src/classes/species.h
  src/classes/species_atomic.cpp
  src/classes/speciesangle.cpp
  src/classes/speciesangle.h
  src/classes/speciesbond.cpp
  src/classes/speciesbond.h
  src/classes/speciesimproper.cpp
  src/classes/speciesimproper.h
  src/classes/speciesintra.cpp
  src/classes/speciesintra.h
  src/classes/speciessite.cpp
  src/classes/speciessite.h
  src/classes/speciestorsion.cpp
  src/classes/speciestorsion.h
  src/gui/CMakeLists.txt
  src/gui/copyspeciestermsdialog.h
  src/gui/copyspeciestermsdialog.ui
  src/gui/copyspeciestermsdialog_funcs.cpp
  src/gui/gui.h
  src/gui/gui.ui
  src/gui/gui_funcs.cpp
  src/gui/menu_species.cpp
  src/gui/models/speciesAtomModel.cpp
  src/gui/selectspeciesdialog_funcs.cpp
  src/gui/speciesviewer.hui
  src/gui/speciesviewer_input.cpp
Labels: 4

#841 Generalise EmpiricalFormula
  src/classes/CMakeLists.txt
  src/classes/empiricalformula.cpp
  src/classes/empiricalformula.h
  src/gui/sitewidget_funcs.cpp
  src/gui/specieseditor_funcs.cpp
  src/gui/specieswidget_funcs.cpp
Labels: 2

#848 Move SpeciesAtom off std::list
  src/classes/species.h
  src/classes/species_atomic.cpp
  src/classes/species_intra.cpp
  src/classes/species_io.cpp
  src/classes/speciesangle.cpp
  src/classes/speciesangle.h
  src/classes/speciesatom.cpp
  src/classes/speciesatom.h
  src/classes/speciesbond.cpp
  src/classes/speciesbond.h
  src/classes/speciesimproper.cpp
  src/classes/speciesimproper.h
  src/classes/speciestorsion.cpp
  src/classes/speciestorsion.h
  src/gui/addforcefieldtermsdialog_funcs.cpp
  src/gui/copyspeciestermsdialog_funcs.cpp
  src/gui/menu_species.cpp
  src/gui/models/speciesAtomModel.cpp
  src/gui/models/speciesAtomModel.h
  src/gui/siteviewer.hui
  src/gui/siteviewer_funcs.cpp
  src/gui/siteviewer_interaction.cpp
  src/gui/sitewidget_funcs.cpp
  src/gui/specieseditor_funcs.cpp
  src/gui/speciestab_geometry.cpp
  src/gui/speciesviewer.hui
  src/gui/speciesviewer_funcs.cpp
  src/gui/speciesviewer_input.cpp
  src/gui/speciesviewer_interaction.cpp
  src/gui/specieswidget_funcs.cpp
  src/main/species.cpp
  src/modules/geomopt/functions.cpp
  unit/classes/cells.cpp
  unit/classes/neutronweights.cpp
  unit/classes/species.cpp
  unit/math/geometryMin.cpp
Labels: 4

#851 Calculate and show total charge on species page.
  src/gui/speciestab.h
  src/gui/speciestab.ui
  src/gui/speciestab_funcs.cpp
  src/gui/speciestab_geometry.cpp
Labels: 2

#853 Bugfix 12/11/21 MD DeltaTSq
  src/modules/md/process.cpp
  tests/md/10.forces
  tests/md/9.restart
Labels: 1

#864 Bugfix 15/11/21 Tab Management
  src/gui/configurationtab.h
  src/gui/configurationtab_funcs.cpp
  src/gui/gui.h
  src/gui/gui_funcs.cpp
  src/gui/gui_simulation.cpp
  src/gui/layertab.h
  src/gui/layertab_funcs.cpp
  src/gui/maintabswidget.hui
  src/gui/maintabswidget_funcs.cpp
  src/gui/menu_configuration.cpp
  src/gui/menu_layer.cpp
  src/gui/menu_species.cpp
  src/gui/speciestab.h
  src/gui/speciestab_funcs.cpp
Labels: 2

#863 Bugfix 15/11/21 Large Molecule Manipulations
  src/classes/box.cpp
  src/classes/box.h
  src/classes/configuration.h
  src/classes/configuration_contents.cpp
  src/classes/molecule.cpp
  src/classes/molecule.h
Labels: 2

#850 Generate Species from CIF
  src/classes/configuration.cpp
  src/classes/configuration.h
  src/classes/configuration_box.cpp
  src/classes/configuration_contents.cpp
  src/classes/configuration_io.cpp
  src/classes/species.h
  src/classes/species_atomic.cpp
  src/classes/species_intra.cpp
  src/classes/speciesintra.cpp
  src/classes/speciesintra.h
  src/data/spacegroups.cpp
  src/data/spacegroups.h
  src/gui/CMakeLists.txt
  src/gui/configurationwidget_funcs.cpp
  src/gui/gui.h
  src/gui/gui.ui
  src/gui/importcifdialog.h
  src/gui/importcifdialog.ui
  src/gui/importcifdialog_funcs.cpp
  src/gui/menu_species.cpp
  src/gui/models/CMakeLists.txt
  src/gui/models/cifAssemblyModel.cpp
  src/gui/models/cifAssemblyModel.h
  src/gui/models/speciesAngleModel.cpp
  src/gui/models/speciesBondModel.cpp
  src/gui/models/speciesImproperModel.cpp
  src/gui/models/speciesTorsionModel.cpp
  src/gui/wizard.hui
  src/gui/wizard_funcs.cpp
  src/io/import/cif.cpp
  src/io/import/cif.h
  src/modules/import_trajectory/process.cpp
  unit/classes/cells.cpp
Labels: 16

#874 Bugfix 18/11/21 PrimitiveList resizing
  src/gui/render/primitivelist.cpp
Labels: 1

#886 Forcefield and SpeciesTab Fixes
  src/classes/species_intra.cpp
  src/classes/species_io.cpp
  src/data/ff/ff.cpp
  src/data/ff/improperterm.cpp
  src/data/ff/library.cpp
  src/gui/menu_species.cpp
  src/gui/models/speciesAngleModel.cpp
  src/gui/models/speciesAngleModel.h
  src/gui/models/speciesBondModel.cpp
  src/gui/models/speciesBondModel.h
  src/gui/models/speciesImproperModel.cpp
  src/gui/models/speciesImproperModel.h
  src/gui/models/speciesTorsionModel.cpp
  src/gui/models/speciesTorsionModel.h
  src/gui/speciestab.h
  src/gui/speciestab.ui
  src/gui/speciestab_funcs.cpp
  src/gui/speciestab_geometry.cpp
  unit/gui/speciestab.cpp
Labels: 2

#885 Add Zhang 2013 ZIF-8 Forcefield
  src/data/ff/library.cpp
  src/data/ff/zhang2013/CMakeLists.txt
  src/data/ff/zhang2013/zhang2013.cpp
  src/data/ff/zhang2013/zhang2013.h
  web/content/docs/ff/builtin/zhang2013.md
Labels: 2

#877 Module Tidying 1/3
  CMakeLists.txt
  benchmark/common/problems.h
  src/classes/coredata.cpp
  src/dissolve-gui.cpp
  src/gui/charts/modulelist.cpp
  src/gui/charts/modulelist.h
  src/gui/modulelisteditor.h
  src/gui/modulelisteditor_funcs.cpp
  src/keywords/modulevector.cpp
  src/main.cpp
  src/main/dissolve.cpp
  src/main/dissolve.h
  src/main/keywords_layer.cpp
  src/main/modules.cpp
  src/module/CMakeLists.txt
  src/module/layer.cpp
  src/module/layer.h
  src/module/list.cpp
  src/module/list.h
  src/modules/CMakeLists.txt
  src/modules/registry.cpp
  src/modules/registry.h
  src/procedure/nodes/nodereference.cpp
  tests/calculate_rdf/rdf.73.restart.test
  tests/calculate_rdf/rdf.txt
  tests/restart/benzene.txt.restart.test
  unit/gui/datamanager.cpp
  unit/gui/forcefieldTab.cpp
  unit/gui/isotopologeSetModel.cpp
Labels: 4

#889 Fix ExponentialSpin widget
  src/gui/forcefieldtab.ui
  src/gui/keywordwidgets/double_funcs.cpp
  src/gui/keywordwidgets/vec3double_funcs.cpp
  src/gui/widgets/exponentialspin.hui
  src/gui/widgets/exponentialspin_funcs.cpp
  src/modules/calculate_sdf/gui/modulewidget_funcs.cpp
Labels: 2

#887 Optimise species loading
  src/classes/coredata.cpp
  src/classes/species.h
  src/classes/species_atomic.cpp
  src/classes/species_intra.cpp
  src/classes/species_io.cpp
  src/classes/speciesangle.cpp
  src/classes/speciesangle.h
  src/classes/speciesatom.cpp
  src/classes/speciesatom.h
  src/classes/speciesbond.cpp
  src/classes/speciesbond.h
  src/classes/speciesimproper.cpp
  src/classes/speciesimproper.h
  src/classes/speciesintra.cpp
  src/classes/speciesintra.h
  src/classes/speciestorsion.cpp
  src/classes/speciestorsion.h
  src/gui/menu_species.cpp
  src/gui/speciestab_geometry.cpp
Labels: 2
