Repository disorderedmaterials/dissolve, pull requests merged in 2021-04, with the labels that each got.

#622 Bugfix 31/03/21 Various
  src/keywords/base.cpp
  src/keywords/speciessitereflist.cpp
  src/keywords/vector_intstring.h
  src/main/dissolve.cpp
  src/modules/rdf/functions.cpp
  tests/atomshake/singlewater.args
  tests/calculate_avgmol/avgmol.args
  tests/calculate_cn/cn.args
  tests/calculate_dangle/dangle.args
  tests/calculate_rdf/rdf.args
  tests/calculate_sdf/sdf.args
  tests/md/benzene.args
  tests/molshake/benzene.args
  tests/restart/benzene.args
Labels: 2

#625 Bugfix 02/04/21 Trajectory Import
  src/classes/configuration_contents.cpp
  src/main/modules.cpp
  src/modules/forces/process.cpp
  src/modules/import/CMakeLists.txt
  src/modules/import/definition.cpp
  src/modules/import/init.cpp
  src/modules/import/process.cpp
  src/modules/import_trajectory/CMakeLists.txt
  src/modules/import_trajectory/core.cpp
  src/modules/import_trajectory/definition.cpp
  src/modules/import_trajectory/importtraj.h
  src/modules/import_trajectory/init.cpp
  src/modules/import_trajectory/process.cpp
  src/modules/neutronsq/process.cpp
  src/modules/xraysq/process.cpp
  tests/calculate_avgmol/avgmol.txt
  tests/calculate_cn/cn.txt
  tests/calculate_dangle/dangle.txt
  tests/calculate_rdf/rdf.txt
  tests/calculate_sdf/sdf.txt
Labels: 2

#631 Bugfix 12-04-21 Trajectory-based Tests
  .azure-pipelines/templates/build-linux-parallel.yml
  .azure-pipelines/templates/build-linux-serial-gui.yml
  .azure-pipelines/templates/build-osx-serial-gui.yml
  .azure-pipelines/templates/build-windows-serial-gui.yml
  src/modules/benchmark/definition.cpp
  src/modules/export_coordinates/definition.cpp
  src/modules/export_pairpotentials/definition.cpp
  src/modules/export_trajectory/definition.cpp
  src/modules/import_trajectory/definition.cpp
  src/modules/skeleton/definition.cpp
  tests/calculate_avgmol/avgmol.txt
  tests/calculate_cn/cn.txt
  tests/calculate_dangle/dangle.txt
  tests/calculate_rdf/rdf.txt
  tests/calculate_sdf/sdf.txt
  web/content/docs/inputfile/configurationblock.md
  web/content/docs/inputfile/speciesblock.md
  web/content/docs/modules/correlation/neutronsq/_index.md
  web/content/docs/modules/correlation/rdf/_index.md
  web/content/docs/modules/correlation/xraysq/_index.md
  web/content/docs/modules/export/_index.md
  web/content/docs/modules/export/exportcoordinates/_index.md
  web/content/docs/modules/export/exportpairpotentials/_index.md
  web/content/docs/modules/export/exporttrajectory/_index.md
  web/content/docs/modules/forcefield/forces/_index.md
  web/content/docs/modules/import/_index.md
  web/content/docs/modules/import/importtrajectory/_index.md
  web/content/docs/reference/fileandformat/coordinates.md
  web/content/docs/reference/fileandformat/coordinatesformat.md
  web/content/docs/reference/fileandformat/data1dformat.md
  web/content/docs/reference/fileandformat/data2d.md
  web/content/docs/reference/fileandformat/data2dformat.md
  web/content/docs/reference/fileandformat/data3d.md
  web/content/docs/reference/fileandformat/data3dformat.md
  web/content/docs/reference/fileandformat/forces.md
  web/content/docs/reference/fileandformat/forcesformat.md
  web/content/docs/reference/fileandformat/pairpotentialformat.md
  web/content/docs/reference/fileandformat/trajectoryformat.md
Labels: 2

#632 Bugfix 13/04/21 String Return From Keywords
  src/base/enumoption.h
  src/base/enumoptions.h
  src/base/enumoptionsbase.h
  src/io/export/coordinates.cpp
  src/io/export/coordinates.h
  src/io/export/data1d.cpp
  src/io/export/data1d.h
  src/io/export/data2d.cpp
  src/io/export/data2d.h
  src/io/export/data3d.cpp
  src/io/export/data3d.h
  src/io/export/forces.cpp
  src/io/export/forces.h
  src/io/export/pairpotential.cpp
  src/io/export/pairpotential.h
  src/io/export/trajectory.cpp
  src/io/export/trajectory.h
  src/io/fileandformat.cpp
  src/io/fileandformat.h
  src/io/import/coordinates.cpp
  src/io/import/coordinates.h
  src/io/import/data1d.cpp
  src/io/import/data1d.h
  src/io/import/data2d.cpp
  src/io/import/data2d.h
  src/io/import/data3d.cpp
  src/io/import/data3d.h
  src/io/import/forces.cpp
  src/io/import/forces.h
  src/io/import/trajectory.cpp
  src/io/import/trajectory.h
Labels: 1

#639 More ListItem Removal
  src/classes/cellarray.cpp
  src/classes/cellarray.h
  src/math/histogram1d.cpp
  src/math/histogram1d.h
  src/math/histogram2d.cpp
  src/math/histogram2d.h
  src/math/histogram3d.cpp
  src/math/histogram3d.h
  src/templates/vector3.h
Labels: 1

#627 Accumulation 1/3 - Data Classes
  src/classes/CMakeLists.txt
  src/classes/partialsetaccumulator.cpp
  src/classes/partialsetaccumulator.h
  src/genericitems/deserialisers.cpp
  src/genericitems/producers.cpp
  src/genericitems/serialisers.cpp
  src/math/CMakeLists.txt
  src/math/sampleddata1d.cpp
  src/math/sampleddata1d.h
  src/math/sampledvector.cpp
  src/math/sampledvector.h
  unit/test_sampledvalues.cpp
Labels: 4

#641 Bugfix 15/04/21 Deserialisation
  .azure-pipelines/templates/build-linux-parallel.yml
  .azure-pipelines/templates/build-linux-serial-gui.yml
  .azure-pipelines/templates/build-osx-serial-gui.yml
  .azure-pipelines/templates/build-windows-serial-gui.yml
  src/genericitems/deserialisers.h
Labels: 1

#628 Accumulation 2/3 - Plottables
  src/classes/partialset.cpp
  src/classes/partialset.h
  src/genericitems/list.h
  src/genericitems/searchers.cpp
  src/gui/render/renderable.h
  src/gui/render/renderabledata1d.cpp
  src/gui/render/renderabledata1d.h
  src/gui/render/renderabledata2d.cpp
  src/gui/render/renderabledata3d.cpp
  src/io/export/data1d.cpp
  src/io/export/data1d.h
  src/io/export/data2d.cpp
  src/io/export/data2d.h
  src/io/export/data3d.cpp
  src/io/export/data3d.h
  src/math/CMakeLists.txt
  src/math/data1d.cpp
  src/math/data1d.h
  src/math/data1dbase.h
  src/math/data2d.cpp
  src/math/data2d.h
  src/math/data2dbase.h
  src/math/data3d.cpp
  src/math/data3d.h
  src/math/data3dbase.h
  src/math/integrator.cpp
  src/math/plottable.cpp
  src/math/plottable.h
  src/math/sampleddata1d.cpp
  src/math/sampleddata1d.h
  src/math/transformer.cpp
  src/procedure/nodes/operateexpression.cpp
Labels: 8

#624 Adding Google benchmark and some initial benchmarks
  CMakeLists.txt
  benchmark/CMakeLists.txt
  benchmark/array/array_benchmark.cpp
  benchmark/benchmark_config.h.in
  benchmark/benchmark_files/large_benchmark.txt
  benchmark/benchmark_files/medium_benchmark.txt
  benchmark/benchmark_files/small_benchmark.txt
  benchmark/benchmarks.cpp
  benchmark/box/box_benchmark.cpp
  benchmark/calculate_gr/calculate_gr_benchmark.cpp
  benchmark/common/problems.h
  benchmark/histogram/histogram_benchmark.cpp
  web/content/docs/startingout/compilation.md
Labels: 2

#652 Bragg Part 2 - Classes
  src/classes/braggreflection.cpp
  src/classes/braggreflection.h
  src/classes/kvector.cpp
  src/classes/kvector.h
  src/genericitems/deserialisers.cpp
  src/genericitems/deserialisers.h
  src/genericitems/producers.cpp
  src/genericitems/serialisers.cpp
  src/genericitems/serialisers.h
  src/math/averaging.h
  src/modules/bragg/functions.cpp
  src/modules/bragg/process.cpp
  src/modules/sq/process.cpp
  src/templates/array2d.h
Labels: 2

#653 Store forces in std::vector
  src/base/processpool.cpp
  src/base/processpool.h
  src/classes/forcekernel.cpp
  src/classes/forcekernel.h
  src/genericitems/deserialisers.cpp
  src/genericitems/producers.cpp
  src/genericitems/serialisers.cpp
  src/io/export/forces.cpp
  src/io/export/forces.h
  src/io/import/forces.cpp
  src/io/import/forces.h
  src/io/import/forces_dlpoly.cpp
  src/io/import/forces_moscito.cpp
  src/io/import/forces_simple.cpp
  src/modules/forces/forces.h
  src/modules/forces/functions.cpp
  src/modules/forces/process.cpp
  src/modules/geomopt/functions.cpp
  src/modules/geomopt/geomopt.h
  src/modules/geomopt/process.cpp
  src/modules/md/functions.cpp
  src/modules/md/md.h
  src/modules/md/process.cpp
Labels: 2

#655 Add energy benchmarks
  benchmark/CMakeLists.txt
  benchmark/benchmark_config.h.in
  benchmark/benchmark_files/argon10k.txt
  benchmark/benchmark_files/argon1k.txt
  benchmark/benchmark_files/argon5k.txt
  benchmark/benchmark_files/hexane1k.txt
  benchmark/benchmark_files/water1k.txt
  benchmark/calculate_gr/calculate_gr_benchmark.cpp
  benchmark/common/problems.h
  benchmark/energy/energy_benchmark.cpp
Labels: 2

#650 Add GitHub action for benchmarking
  .github/workflows/benchmark_linux.yml
Labels: 2

#658 Bugfix 26-04-21 Hexane Benchmarks
  benchmark/benchmark_files/hexane1k.txt
  examples/benchmark/hexane100k.txt
  examples/benchmark/hexane10k.txt
  examples/benchmark/hexane1k.txt
Labels: 1

#659 Parallel energy routines
  benchmark/energy/energy_benchmark.cpp
  conanfile.txt
  src/base/CMakeLists.txt
  src/classes/CMakeLists.txt
  src/classes/energykernel.cpp
  src/classes/energykernel.h
  src/classes/potentialmap.cpp
  src/classes/potentialmap.h
  src/classes/scaledenergykernel.cpp
  src/modules/CMakeLists.txt
  src/modules/atomshake/process.cpp
  src/modules/energy/functions.cpp
  src/modules/energy/process.cpp
  src/modules/intrashake/process.cpp
  src/modules/molshake/process.cpp
  src/modules/rdf/functions.cpp
  src/templates/algorithms.h
  src/templates/parallel_defs.h
  src/templates/parallel_tbb.h
  src/templates/tbb-defs.h
  src/templates/tbb-fallbacks.h
Labels: 4
