Repository disorderedmaterials/dissolve, pull requests merged in 2021-03, with the labels that each got.

#569 Bugfix 03-03-21 Const TableWidgetUpdater
  src/gui/addconfigurationwizard_funcs.cpp
  src/gui/configurationtab_funcs.cpp
  src/gui/datamanagerdialog_funcs.cpp
  src/gui/forcefieldtab_funcs.cpp
  src/gui/helpers/tablewidgetupdater.h
  src/gui/keywordwidgets/expressionvariablevector_funcs.cpp
  src/gui/keywordwidgets/modulegroups_funcs.cpp
  src/gui/keywordwidgets/speciessite_funcs.cpp
  src/gui/keywordwidgets/speciessitereflist_funcs.cpp
  src/gui/speciestab.h
  src/gui/speciestab_geometry.cpp
Labels: 2

#570 Change cell array to vector of unique pointers instead of c array of raw pointers
  src/classes/cell.cpp
  src/classes/cell.h
  src/classes/cellarray.cpp
  src/classes/cellarray.h
Labels: 2

#560 Simplify WindowFunction class
  src/gui/keywordwidgets/CMakeLists.txt
  src/gui/keywordwidgets/widget_funcs.cpp
  src/gui/keywordwidgets/widgets.h
  src/gui/keywordwidgets/windowfunction.hui
  src/gui/keywordwidgets/windowfunction_funcs.cpp
  src/keywords/CMakeLists.txt
  src/keywords/base.h
  src/keywords/types.h
  src/keywords/windowfunction.cpp
  src/keywords/windowfunction.h
  src/math/windowfunction.cpp
  src/math/windowfunction.h
  src/modules/epsr/process.cpp
  src/modules/neutronsq/init.cpp
  src/modules/neutronsq/process.cpp
  src/modules/sq/init.cpp
  src/modules/sq/process.cpp
  src/modules/xraysq/init.cpp
  src/modules/xraysq/process.cpp
Labels: 2

#573 Remove ListItem inheritence from Species and SpeciesAtom
  src/classes/atom.h
  src/classes/configuration.h
  src/classes/configuration_contents.cpp
  src/classes/configuration_io.cpp
  src/classes/coredata.cpp
  src/classes/coredata.h
  src/classes/empiricalformula.cpp
  src/classes/neutronweights.cpp
  src/classes/species.cpp
  src/classes/species.h
  src/classes/species_atomic.cpp
  src/classes/species_intra.cpp
  src/classes/species_io.cpp
  src/classes/species_transform.cpp
  src/classes/speciesatom.cpp
  src/classes/speciesatom.h
  src/classes/speciessite.cpp
  src/classes/xrayweights.cpp
  src/data/ff/ff.cpp
  src/data/ff/ff.h
  src/data/ff/uff/uff.cpp
  src/data/ff/uff/uff.h
  src/gui/addforcefieldtermswizard_funcs.cpp
  src/gui/getspeciesnamedialog_funcs.cpp
  src/gui/helpers/comboboxupdater.h
  src/gui/helpers/listwidgetupdater.h
  src/gui/helpers/tablewidgetupdater.h
  src/gui/importspecieswizard_funcs.cpp
  src/gui/keywordwidgets/isotopologueset_funcs.cpp
  src/gui/keywordwidgets/speciessite_funcs.cpp
  src/gui/keywordwidgets/speciessitereflist_funcs.cpp
  src/gui/maintabswidget_funcs.cpp
  src/gui/render/renderablespecies.cpp
  src/gui/siteviewer_interaction.cpp
  src/gui/speciestab_geometry.cpp
  src/gui/speciesviewer_interaction.cpp
  src/main/dissolve.h
  src/main/io.cpp
  src/main/simulation.cpp
  src/main/species.cpp
  src/modules/calculate_avgmol/process.cpp
  src/modules/calculate_sdf/gui/modulewidget_funcs.cpp
  src/modules/checkspecies/process.cpp
  src/modules/energy/functions.cpp
  src/modules/forces/functions.cpp
  src/modules/geomopt/functions.cpp
  src/templates/orderedpointerdataarray.h
Labels: 4

#585 Remove list item inheritance from species site
  src/classes/species.h
  src/classes/species_io.cpp
  src/classes/species_site.cpp
  src/classes/speciessite.cpp
  src/classes/speciessite.h
  src/gui/helpers/listwidgetupdater.h
  src/gui/keywordwidgets/speciessite_funcs.cpp
  src/gui/keywordwidgets/speciessitereflist_funcs.cpp
  src/gui/speciestab_sites.cpp
  src/keywords/speciessite.cpp
  src/keywords/speciessitereflist.cpp
Labels: 2

#584 Remove list item inheritance from species info
  src/classes/configuration.h
  src/classes/configuration_contents.cpp
  src/classes/speciesinfo.cpp
  src/classes/speciesinfo.h
  src/classes/xrayweights.cpp
  src/classes/xrayweights.h
  src/gui/delegates/usedspeciescombo_funcs.cpp
  src/main/simulation.cpp
  src/modules/intrashake/process.cpp
  src/modules/rdf/functions.cpp
Labels: 2

#592 Remove ordered pointer list
  src/classes/changestore.cpp
  src/classes/energykernel.h
  src/classes/forcekernel.h
  src/classes/regionaldistributor.cpp
  src/classes/regionaldistributor.h
  src/templates/orderedpointerlist.h
Labels: 1

#593 Removing dead code
  src/classes/atomtypedata.cpp
  src/classes/energykernel.cpp
  src/gui/addconfigurationwizard_funcs.cpp
  src/gui/addforcefieldtermswizard_funcs.cpp
  src/gui/charts/chart_funcs.cpp
  src/gui/charts/moduleinsertionblock_funcs.cpp
  src/gui/charts/modulelist.cpp
  src/gui/charts/procedure.cpp
  src/gui/dataviewer_input.cpp
  src/gui/dataviewer_interaction.cpp
  src/gui/dataviewer_render.cpp
  src/gui/datawidget_funcs.cpp
  src/gui/delegates/isotopecombo_funcs.cpp
  src/gui/forcefieldtab_funcs.cpp
  src/gui/getgizmonamedialog_funcs.cpp
  src/gui/keywordwidgets/pairbroadeningfunction_funcs.cpp
  src/gui/procedureeditor.h
  src/gui/procedureeditor_funcs.cpp
  src/gui/render/axes.cpp
  src/gui/render/fontinstance.cpp
  src/gui/render/linestipple.cpp
  src/gui/render/primitive.cpp
  src/gui/render/renderabledata2d.cpp
  src/gui/render/renderablespeciessite.cpp
  src/gui/render/view.cpp
  src/gui/siteviewer_funcs.cpp
  src/gui/sitewidget_funcs.cpp
  src/gui/speciestab_geometry.cpp
  src/gui/speciesviewer_funcs.cpp
  src/gui/viewer_input.cpp
  src/gui/viewer_query.cpp
  src/gui/viewer_render.cpp
  src/gui/widgets/elementselector_funcs.cpp
  src/gui/widgets/exponentialspin.hui
  src/gui/widgets/exponentialspin_funcs.cpp
  src/gui/widgets/mimetreewidget_funcs.cpp
  src/io/export/data2d.cpp
  src/io/export/trajectory.cpp
  src/io/import/coordinates_epsr.cpp
  src/main/comms.cpp
  src/math/data1d.cpp
  src/math/interpolator.cpp
  src/math/matrix4.cpp
  src/math/sd.h
  src/math/svd.cpp
  src/modules/calculate_axisangle/init.cpp
  src/modules/energy/process.cpp
  src/modules/epsr/functions.cpp
  src/modules/epsr/process.cpp
  src/modules/geomopt/geomopt.h
  src/procedure/nodes/fit1d.cpp
Labels: 1

#576 Move Renderable and RenderableGroup to std::vector
  src/gui/configurationviewer.hui
  src/gui/configurationviewer_funcs.cpp
  src/gui/dataviewer.hui
  src/gui/dataviewer_contextmenu.cpp
  src/gui/dataviewer_input.cpp
  src/gui/dataviewer_render.cpp
  src/gui/datawidget.h
  src/gui/datawidget_funcs.cpp
  src/gui/forcefieldtab_funcs.cpp
  src/gui/graphgizmo_funcs.cpp
  src/gui/helpers/treewidgetupdater.h
  src/gui/integrator1dgizmo_funcs.cpp
  src/gui/render/renderable.cpp
  src/gui/render/renderable.h
  src/gui/render/renderablefactory.cpp
  src/gui/render/renderablefactory.h
  src/gui/render/renderablegroup.cpp
  src/gui/render/renderablegroup.h
  src/gui/render/renderablegroupmanager.cpp
  src/gui/render/renderablegroupmanager.h
  src/gui/render/view.cpp
  src/gui/render/view.h
  src/gui/siteviewer.hui
  src/gui/siteviewer_funcs.cpp
  src/gui/speciesviewer.hui
  src/gui/speciesviewer_funcs.cpp
  src/gui/viewer.hui
  src/gui/viewer_render.cpp
  src/gui/viewer_renderables.cpp
  src/modules/bragg/gui/modulewidget_funcs.cpp
  src/modules/calculate_angle/gui/modulewidget_funcs.cpp
  src/modules/calculate_axisangle/gui/modulewidget_funcs.cpp
  src/modules/calculate_cn/gui/modulewidget_funcs.cpp
  src/modules/calculate_dangle/gui/modulewidget_funcs.cpp
  src/modules/calculate_rdf/gui/modulewidget_funcs.cpp
  src/modules/calculate_sdf/gui/modulewidget.h
  src/modules/calculate_sdf/gui/modulewidget_funcs.cpp
  src/modules/energy/gui/modulewidget_funcs.cpp
  src/modules/epsr/gui/modulewidget_funcs.cpp
  src/modules/neutronsq/gui/modulewidget_funcs.cpp
  src/modules/rdf/gui/modulewidget_funcs.cpp
  src/modules/sq/gui/modulewidget_funcs.cpp
  src/modules/xraysq/gui/modulewidget_funcs.cpp
Labels: 4

#602 Bugfix 19-03-21 Missing Renderables
  src/gui/siteviewer_funcs.cpp
  src/gui/speciesviewer_funcs.cpp
Labels: 1

#581 Use template-guided renderable creation
  src/gui/dataviewer_contextmenu.cpp
  src/gui/forcefieldtab_funcs.cpp
  src/gui/graphgizmo_funcs.cpp
  src/gui/integrator1dgizmo_funcs.cpp
  src/gui/render/CMakeLists.txt
  src/gui/render/renderablefactory.cpp
  src/gui/render/renderablefactory.h
  src/gui/render/renderablespecies.cpp
  src/gui/render/renderablespecies.h
  src/gui/siteviewer_funcs.cpp
  src/gui/speciesviewer_funcs.cpp
  src/gui/viewer.hui
  src/gui/viewer_renderables.cpp
  src/modules/bragg/gui/modulewidget_funcs.cpp
  src/modules/calculate_angle/gui/modulewidget_funcs.cpp
  src/modules/calculate_axisangle/gui/modulewidget_funcs.cpp
  src/modules/calculate_cn/gui/modulewidget_funcs.cpp
  src/modules/calculate_dangle/gui/modulewidget_funcs.cpp
  src/modules/calculate_rdf/gui/modulewidget_funcs.cpp
  src/modules/calculate_sdf/gui/modulewidget.h
  src/modules/calculate_sdf/gui/modulewidget_funcs.cpp
  src/modules/energy/gui/modulewidget_funcs.cpp
  src/modules/epsr/gui/modulewidget_funcs.cpp
  src/modules/neutronsq/gui/modulewidget_funcs.cpp
  src/modules/rdf/gui/modulewidget_funcs.cpp
  src/modules/sq/gui/modulewidget_funcs.cpp
  src/modules/xraysq/gui/modulewidget_funcs.cpp
Labels: 8

#610 Fix iterator invalidation on Species vectors
  src/classes/coredata.cpp
  src/classes/coredata.h
  src/gui/delegates/intraformcombo.hui
  src/gui/delegates/intraformcombo_funcs.cpp
  src/gui/helpers/combopopulator.h
  src/gui/helpers/tablewidgetupdater.h
  src/gui/helpers/treewidgetupdater.h
  src/main/dissolve.h
  src/main/masterterms.cpp
Labels: 1, Priority: High, Type: Bug

#609 Bugfix 22/03/21 Species Atoms/Bond Handling
  src/classes/species.h
  src/classes/species_atomic.cpp
  src/classes/species_intra.cpp
  src/classes/speciesatom.cpp
  src/classes/speciesatom.h
  src/gui/menu_species.cpp
Labels: 4

#613 Bugfix 24/03/21 Charges and Species Atoms
  src/classes/pairpotential.cpp
  src/classes/species_ff.cpp
  src/data/ff/ff.cpp
  src/data/ff/ff.h
  src/gui/addforcefieldtermswizard.ui
  src/gui/addforcefieldtermswizard_funcs.cpp
  src/gui/speciestab_geometry.cpp
Labels: 2

#614 Force Fixes
  src/modules/forces/functions.cpp
  src/modules/geomopt/functions.cpp
  src/modules/geomopt/geomopt.h
Labels: 4

#615 Bugfix 25-03-21 Various
  src/base/lineparser.cpp
  src/dissolve-gui.cpp
Labels: 1

#616 NETA Tidying / Modernisation
  src/classes/speciesring.cpp
  src/classes/speciesring.h
  src/neta/NETAErrorListeners.cpp
  src/neta/NETALexer.g4
  src/neta/NETAVisitor.cpp
  src/neta/connection.cpp
  src/neta/connection.h
  src/neta/neta.cpp
  src/neta/neta.h
  src/neta/node.cpp
  src/neta/node.h
  src/neta/or.cpp
  src/neta/or.h
  src/neta/presence.cpp
  src/neta/presence.h
  src/neta/ring.cpp
  src/neta/ring.h
  src/neta/root.cpp
  src/neta/root.h
  unit/test_neta.cpp
Labels: 4

#618 NETA Geometry
  src/classes/speciesatom.cpp
  src/classes/speciesatom.h
  src/data/ff/ff.cpp
  src/data/ff/ff.h
  src/neta/NETAParser.g4
  src/neta/NETAVisitor.cpp
  src/neta/NETAVisitor.h
  src/neta/connection.cpp
  src/neta/connection.h
  src/neta/node.cpp
  src/neta/node.h
  src/neta/ring.h
  src/neta/root.cpp
  src/neta/root.h
  unit/test_neta.cpp
Labels: 2
