Repository disorderedmaterials/dissolve, pull requests merged in 2021-08, with the labels that each got.

#761 Remove ListItem dependency from Isotopologues and IsotopeData
  src/classes/isotopedata.h
  src/classes/isotopologue.cpp
  src/classes/isotopologue.h
  src/classes/isotopologues.cpp
  src/classes/species.cpp
  src/classes/species.h
  src/classes/species_io.cpp
  src/classes/species_isotopologues.cpp
  src/gui/keywordwidgets/isotopologueset_funcs.cpp
  src/gui/models/speciesIsoModel.cpp
Labels: 2

#765 Remove ListItem dependency from Modules
  src/gui/charts/modulelist.cpp
  src/gui/getmodulelayernamedialog.h
  src/gui/getmodulelayernamedialog_funcs.cpp
  src/gui/keywordwidgets/modulegroups_funcs.cpp
  src/gui/maintabswidget_funcs.cpp
  src/gui/modulelisteditor_funcs.cpp
  src/keywords/modulegroups.cpp
  src/main/dissolve.h
  src/main/io.cpp
  src/main/layers.cpp
  src/main/modules.cpp
  src/main/simulation.cpp
  src/module/group.cpp
  src/module/group.h
  src/module/groups.cpp
  src/module/groups.h
  src/module/layer.cpp
  src/module/layer.h
  src/module/list.cpp
  src/module/list.h
  src/module/module.h
  src/templates/algorithms.h
Labels: 4

#766 Bugfix 04/08/21 GUI Input File Loading
  src/gui/gui_funcs.cpp
Labels: 1

#754 Use Centralised Scripts
  .azure-pipelines/templates/create-release.yml
  .azure-pipelines/templates/package-linux.yml
  .azure-pipelines/templates/package-osx.yml
  .travis.yml
  ci/scripts/prep-appimage
  ci/scripts/prep-dmg
  ci/scripts/prune-continuous
  ci/scripts/update-release
  dissolve.kdev4
Labels: 1

#767 Cylindrical Regions
  src/classes/CMakeLists.txt
  src/classes/box.cpp
  src/classes/region.cpp
  src/classes/region.h
  src/keywords/node.cpp
  src/keywords/node.h
  src/keywords/nodeandinteger.cpp
  src/keywords/nodeandinteger.h
  src/procedure/nodes/CMakeLists.txt
  src/procedure/nodes/add.cpp
  src/procedure/nodes/cylindricalregion.cpp
  src/procedure/nodes/cylindricalregion.h
  src/procedure/nodes/generalregion.cpp
  src/procedure/nodes/generalregion.h
  src/procedure/nodes/node.cpp
  src/procedure/nodes/node.h
  src/procedure/nodes/nodes.h
  src/procedure/nodes/pickcylinder.cpp
  src/procedure/nodes/pickregion.cpp
  src/procedure/nodes/pickregion.h
  src/procedure/nodes/regionbase.cpp
  src/procedure/nodes/regionbase.h
  src/procedure/nodes/sequence.cpp
  web/content/docs/inputfile/configurationblock.md
  web/content/docs/procedures/nodes/generalregion.md
  web/content/docs/reference/boxactionstyle.md
  web/content/docs/reference/positioningtype.md
  web/content/examples/argon/step3.md
  web/content/examples/benzene/step2.md
  web/content/examples/silica_bulk/step2.md
  web/content/examples/water/step2.md
Labels: 4
