Repository disorderedmaterials/dissolve, pull requests merged in 2021-12, with the labels that each got.

#898 Bugfix 2/12/21 Keywords
  src/gui/keywordwidgets/base.cpp
  src/gui/keywordwidgets/enumoptions_funcs.cpp
  src/keywords/enumoptions.h
  src/keywords/function1d.cpp
  src/modules/rdf/rdf.cpp
Labels: 1

#894 Bugfix 02/12/21 Intramolecular g(r)
  src/modules/rdf/functions.cpp
Labels: 1

#893 Display population in the configuration tab
  src/gui/configurationtab.ui
  src/gui/configurationtab_funcs.cpp
Labels: 2

#900 Bugfix 03/12/21 Layer Creation
  src/gui/menu_layer.cpp
  src/gui/modulecontrolwidget_funcs.cpp
  src/keywords/store.cpp
  src/keywords/store.h
  src/modules/calculate_avgmol/avgmol.h
Labels: 2

#903 Bugfix 07/12/21 Misc
  src/classes/configuration.cpp
  src/gui/speciesviewer_interaction.cpp
Labels: 1

#909 ETA Calculation
  src/gui/gui.h
  src/gui/gui_funcs.cpp
  src/gui/icons/general_clock.svg
  src/gui/main.qrc
  src/main/dissolve.h
  src/main/simulation.cpp
Labels: 2

#910 Species Editor Modifications
  src/classes/species.h
  src/classes/species_ff.cpp
  src/gui/render/renderablespecies.cpp
  src/gui/specieseditor.h
  src/gui/specieseditor.ui
  src/gui/specieseditor_funcs.cpp
  src/gui/speciesviewer_funcs.cpp
Labels: 2

#911 ExpressionVariable Model
  src/expression/ExpressionVisitor.cpp
  src/expression/binary.cpp
  src/expression/binary.h
  src/expression/expression.cpp
  src/expression/expression.h
  src/expression/function.cpp
  src/expression/function.h
  src/expression/node.h
  src/expression/number.cpp
  src/expression/number.h
  src/expression/reference.cpp
  src/expression/reference.h
  src/expression/root.cpp
  src/expression/root.h
  src/expression/unary.cpp
  src/expression/unary.h
  src/gui/delegates/exponentialspin.hui
  src/gui/delegates/exponentialspin_funcs.cpp
  src/gui/keywordwidgets/expressionvariablevector.h
  src/gui/keywordwidgets/expressionvariablevector.ui
  src/gui/keywordwidgets/expressionvariablevector_funcs.cpp
  src/gui/models/CMakeLists.txt
  src/gui/models/expressionVariableVectorModel.cpp
  src/gui/models/expressionVariableVectorModel.h
  src/gui/widgets/exponentialspin_funcs.cpp
  src/keywords/expressionvariablevector.cpp
  src/keywords/expressionvariablevector.h
  src/procedure/nodes/node.cpp
  src/procedure/nodes/node.h
  src/procedure/nodes/parameters.cpp
  src/procedure/nodes/parameters.h
  src/procedure/nodes/sequence.cpp
  unit/gui/CMakeLists.txt
  unit/gui/expressionVariableVectorModel.cpp
  unit/math/expression.cpp
Labels: 4
