Repository disorderedmaterials/dissolve, pull requests merged in 2021-07, with the labels that each got.

#741 Pick Species
  src/classes/configuration.h
  src/classes/configuration_contents.cpp
  src/classes/sitestack.cpp
  src/modules/forces/functions.cpp
  src/procedure/nodes/CMakeLists.txt
  src/procedure/nodes/dynamicsite.cpp
  src/procedure/nodes/node.cpp
  src/procedure/nodes/node.h
  src/procedure/nodes/nodes.h
  src/procedure/nodes/pick.cpp
  src/procedure/nodes/pick.h
  src/procedure/nodes/pickbase.cpp
  src/procedure/nodes/pickbase.h
  src/procedure/nodes/pickcylinder.cpp
  src/procedure/nodes/pickcylinder.h
  src/procedure/nodes/removespecies.cpp
  src/procedure/nodes/removespecies.h
  src/procedure/nodes/select.cpp
  src/procedure/nodes/sequence.cpp
  web/content/docs/procedures/nodes/pickcylinder.md
  web/content/docs/procedures/nodes/picknode.md
  web/content/docs/procedures/nodes/removespeciesnode.md
Labels: 4

#738 Dark Mode Cosmetics
  src/gui/charts/moduleblock_funcs.cpp
  src/gui/charts/modulelist.cpp
  src/gui/charts/modulelist.h
  src/gui/charts/procedure.cpp
  src/gui/charts/procedure.h
  src/gui/charts/procedurenode.h
  src/gui/charts/procedurenode_funcs.cpp
  src/gui/maintabswidget_funcs.cpp
  src/gui/modulelisteditor_funcs.cpp
  src/gui/modulewidget.cpp
  src/gui/modulewidget.h
  src/gui/outputhandler.hui
  src/gui/outputhandler_funcs.cpp
Labels: 1

#739 Remove System Templates
  src/gui/CMakeLists.txt
  src/gui/gui.h
  src/gui/gui.ui
  src/gui/gui_funcs.cpp
  src/gui/main.qrc
  src/gui/menu_file.cpp
  src/gui/selectsystemtemplatedialog.h
  src/gui/selectsystemtemplatedialog.ui
  src/gui/selectsystemtemplatedialog_funcs.cpp
  src/gui/systemtemplate.cpp
  src/gui/systemtemplate.h
  src/gui/systemtemplates/simple_one/icon.svg
  src/gui/systemtemplates/simple_one/info.xml
  src/gui/systemtemplates/simple_one/input.txt
  src/gui/systemtemplates/simple_two/icon.svg
  src/gui/systemtemplates/simple_two/info.xml
  src/gui/systemtemplates/simple_two/input.txt
Labels: 1

#745 Input File Writing
  src/classes/species_intra.cpp
  src/classes/speciessite.cpp
  src/templates/algorithms.h
Labels: 1

#750 Box Updates 1
  benchmark/box/box_benchmark.cpp
  src/classes/box.h
  src/classes/box_cubic.cpp
  src/classes/box_monoclinic.cpp
  src/classes/box_nonperiodic.cpp
  src/classes/box_orthorhombic.cpp
  src/classes/box_triclinic.cpp
Labels: 2

#748 Transmute Species
  src/gui/helpers/comboboxcontroller.h
  src/gui/keywordwidgets/node_funcs.cpp
  src/gui/keywordwidgets/nodeandinteger_funcs.cpp
  src/keywords/speciesvector.cpp
  src/procedure/nodes/CMakeLists.txt
  src/procedure/nodes/node.cpp
  src/procedure/nodes/node.h
  src/procedure/nodes/nodes.h
  src/procedure/nodes/pick.cpp
  src/procedure/nodes/pickbase.cpp
  src/procedure/nodes/pickbase.h
  src/procedure/nodes/pickcylinder.cpp
  src/procedure/nodes/pickproximity.cpp
  src/procedure/nodes/pickproximity.h
  src/procedure/nodes/remove.cpp
  src/procedure/nodes/sequence.cpp
  src/procedure/nodes/sequence.h
  src/procedure/nodes/transmute.cpp
  src/procedure/nodes/transmute.h
Labels: 4

#752 Module Targets 1
  src/gui/charts/moduleblock_funcs.cpp
  src/gui/keywordwidgets/CMakeLists.txt
  src/gui/keywordwidgets/atomtypeselection_funcs.cpp
  src/gui/keywordwidgets/configurationvector.h
  src/gui/keywordwidgets/configurationvector.ui
  src/gui/keywordwidgets/configurationvector_funcs.cpp
  src/gui/keywordwidgets/modulegroups_funcs.cpp
  src/gui/keywordwidgets/modulevector_funcs.cpp
  src/gui/keywordwidgets/nodevector_funcs.cpp
  src/gui/keywordwidgets/speciessitevector_funcs.cpp
  src/gui/keywordwidgets/speciesvector_funcs.cpp
  src/gui/keywordwidgets/widget_funcs.cpp
  src/gui/keywordwidgets/widgets.h
  src/gui/modulecontrolwidget.h
  src/gui/modulecontrolwidget_funcs.cpp
  src/keywords/CMakeLists.txt
  src/keywords/base.h
  src/keywords/configurationvector.cpp
  src/keywords/configurationvector.h
  src/keywords/modulevector.cpp
  src/module/module.cpp
  src/module/module.h
  src/modules/accumulate/core.cpp
  src/modules/analyse/process.cpp
  src/modules/atomshake/process.cpp
  src/modules/benchmark/process.cpp
  src/modules/bragg/process.cpp
  src/modules/calculate_angle/process.cpp
  src/modules/calculate_avgmol/process.cpp
  src/modules/calculate_axisangle/process.cpp
  src/modules/calculate_dangle/process.cpp
  src/modules/calculate_rdf/process.cpp
  src/modules/calculate_sdf/process.cpp
  src/modules/checks/process.cpp
  src/modules/energy/process.cpp
  src/modules/export_coordinates/process.cpp
  src/modules/export_trajectory/process.cpp
  src/modules/forces/process.cpp
  src/modules/geomopt/process.cpp
  src/modules/import_trajectory/process.cpp
  src/modules/intrashake/process.cpp
  src/modules/md/process.cpp
  src/modules/molshake/process.cpp
  src/modules/neutronsq/init.cpp
  src/modules/rdf/process.cpp
  src/modules/skeleton/process.cpp
  src/modules/test/process.cpp
  src/templates/algorithms.h
Labels: 4

#753 Box Scaling
  src/classes/box.cpp
  src/classes/box.h
  src/classes/cellarray.cpp
  src/classes/cellarray.h
  src/classes/configuration.h
  src/classes/configuration_box.cpp
  src/classes/configuration_contents.cpp
  src/classes/configuration_io.cpp
  src/procedure/nodes/add.cpp
  src/templates/vector3.h
  unit/test_box.cpp
  web/content/docs/procedures/nodes/addnode.md
Labels: 4

#757 Remove GUI Start Screen
  icon/simple.svg
  src/dissolve-gui.cpp
  src/gui/CMakeLists.txt
  src/gui/configurationtab_funcs.cpp
  src/gui/forcefieldtab.h
  src/gui/forcefieldtab_funcs.cpp
  src/gui/gui.h
  src/gui/gui.ui
  src/gui/gui_funcs.cpp
  src/gui/gui_simulation.cpp
  src/gui/gui_start.cpp
  src/gui/icons/simple.png
  src/gui/icons/tabs_configuration.svg
  src/gui/icons/tabs_ff.svg
  src/gui/icons/tabs_messages.svg
  src/gui/icons/tabs_modulelayer.svg
  src/gui/icons/tabs_modulelayer_disabled.svg
  src/gui/icons/tabs_species.svg
  src/gui/layertab_funcs.cpp
  src/gui/main.qrc
  src/gui/maintab.cpp
  src/gui/maintab.h
  src/gui/maintabswidget.hui
  src/gui/maintabswidget_funcs.cpp
  src/gui/menu_configuration.cpp
  src/gui/menu_file.cpp
  src/gui/menu_help.cpp
  src/gui/menu_layer.cpp
  src/gui/menu_simulation.cpp
  src/gui/menu_species.cpp
  src/gui/messagestab.h
  src/gui/messagestab.ui
  src/gui/messagestab_funcs.cpp
  src/gui/speciestab_funcs.cpp
  src/gui/workspacetab.h
  src/gui/workspacetab_funcs.cpp
  src/main.cpp
  src/main/cli.cpp
  src/main/dissolve.h
  src/main/modules.cpp
Labels: 4

#758 Remove ListItem Depedency from ObjectFactory
  src/gui/render/primitiveassembly.cpp
  src/gui/render/primitiveassembly.h
  src/templates/factory.h
Labels: 2

#759 Remove list dependency from Primitive rendering
  src/gui/render/primitive.cpp
  src/gui/render/primitive.h
  src/gui/render/primitiveassembly.cpp
  src/gui/render/primitiveassembly.h
  src/gui/render/primitiveinstance.cpp
  src/gui/render/primitiveinstance.h
  src/gui/render/primitivelist.cpp
  src/gui/render/primitivelist.h
Labels: 2

#762 Remove List dependency from Gizmo
  src/gui/gizmo.cpp
  src/gui/gizmo.h
  src/gui/workspacetab.h
  src/gui/workspacetab_funcs.cpp
Labels: 2
