Repository disorderedmaterials/dissolve, pull requests merged in 2021-05, with the labels that each got.

#664 Parallel force calculations
  benchmark/CMakeLists.txt
  benchmark/forces/forces_benchmark.cpp
  src/classes/forcekernel.cpp
  src/classes/forcekernel.h
  src/classes/potentialmap.cpp
  src/classes/potentialmap.h
  src/modules/forces/functions.cpp
  src/modules/forces/process.cpp
  src/templates/algorithms.h
  src/templates/combinable.h
  src/templates/parallel_tbb.h
  src/templates/tbb-defs.h
  src/templates/tbb-fallbacks.h
Labels: 4

#669 Bugfix 07/05/21 System Tests
  src/modules/accumulate/init.cpp
  tests/CMakeLists.txt
  tests/accumulate/accumulate.txt
Labels: 2

#668 Bugfix 08/05/21 Data Export
  src/classes/partialsetaccumulator.cpp
  src/modules/calculate_angle/init.cpp
  src/modules/calculate_axisangle/init.cpp
  src/modules/calculate_dangle/init.cpp
  src/modules/calculate_rdf/init.cpp
  src/procedure/nodes/process1d.cpp
  src/procedure/nodes/process1d.h
  src/procedure/nodes/process2d.cpp
  src/procedure/nodes/process2d.h
  src/procedure/nodes/process3d.cpp
  src/procedure/nodes/process3d.h
  web/content/docs/procedures/nodes/process1dnode.md
  web/content/docs/procedures/nodes/process2dnode.md
  web/content/docs/procedures/nodes/process3dnode.md
Labels: 1

#660 UFF4MOF Testing
  src/classes/atomtype.cpp
  src/classes/pairpotential.cpp
  src/classes/species.cpp
  src/classes/species.h
  src/classes/species_ff.cpp
  src/classes/species_intra.cpp
  src/classes/species_io.cpp
  src/data/ff/ff.cpp
  src/data/ff/ff.h
  src/data/ff/kulmala2010/kulmala2010.cpp
  src/data/ff/library.cpp
  src/data/ff/ludwig/ntf2.cpp
  src/data/ff/ludwig/py4oh.cpp
  src/data/ff/ludwig/py5.cpp
  src/data/ff/oplsaa2005/base.cpp
  src/data/ff/pcl2019/base.cpp
  src/data/ff/spcfw/spcfw.cpp
  src/data/ff/strader2002/dmso.cpp
  src/data/ff/uff/uff.cpp
  src/data/ff/uff/uff.h
  src/data/ff/uff/uff4mof.cpp
  src/data/ff/uff/uff4mof.h
  src/data/ff/uff/uffatomtype.cpp
  src/data/ff/uff/uffatomtype.h
  src/data/ff/xml/base.cpp
  src/gui/gui.h
  src/gui/gui.ui
  src/gui/gui_funcs.cpp
  src/gui/menu_species.cpp
  src/io/import/forces.cpp
  src/main/pairpotentials.cpp
  src/main/species.cpp
  src/neta/NETAVisitor.cpp
  tests/ff/CMakeLists.txt
  tests/ff/uff-nmethylformamide.txt
  tests/ff/uff4mof-mof5.txt
  unit/test_neta.cpp
  web/content/docs/ff/uff4mof.md
Labels: 8

#657 Remove Array 1
  src/base/processgroup.cpp
  src/base/processgroup.h
  src/base/processpool.cpp
  src/base/processpool.h
  src/classes/CMakeLists.txt
  src/classes/celldistributor.cpp
  src/classes/celldistributor.h
  src/classes/configuration.cpp
  src/classes/configuration.h
  src/classes/configuration_contents.cpp
  src/classes/coordinateset.cpp
  src/classes/coordinateset.h
  src/classes/distributor.cpp
  src/classes/distributor.h
  src/classes/moleculedistributor.cpp
  src/classes/moleculedistributor.h
  src/classes/regionaldistributor.cpp
  src/classes/regionaldistributor.h
  src/classes/scatteringmatrix.cpp
  src/classes/scatteringmatrix.h
  src/classes/sitestack.cpp
  src/classes/sitestack.h
  src/classes/species.cpp
  src/classes/species.h
  src/classes/species_io.cpp
  src/classes/speciessite.cpp
  src/classes/speciessite.h
  src/genericitems/deserialisers.cpp
  src/genericitems/producers.cpp
  src/genericitems/serialisers.cpp
  src/gui/render/renderabledata2d.cpp
  src/gui/render/renderabledata3d.cpp
  src/gui/render/renderablegroupmanager.cpp
  src/gui/render/renderablegroupmanager.h
  src/gui/speciestab_sites.cpp
  src/io/import/coordinates.cpp
  src/io/import/coordinates.h
  src/io/import/coordinates_dlpoly.cpp
  src/io/import/coordinates_epsr.cpp
  src/io/import/coordinates_moscito.cpp
  src/io/import/coordinates_xyz.cpp
  src/main/comms.cpp
  src/math/CMakeLists.txt
  src/math/extrema.cpp
  src/math/extrema.h
  src/math/sd.h
  src/math/svd.cpp
  src/modules/bragg/functions.cpp
  src/modules/forces/forces.h
  src/modules/forces/functions.cpp
  src/procedure/nodes/addspecies.cpp
  src/templates/simplex.h
Labels: 2

#670 Remove Array 2
  src/classes/site.h
  src/classes/sitestack.cpp
  src/classes/sitestack.h
  src/gui/render/colourdefinition.cpp
  src/gui/render/colourdefinition.h
  src/gui/render/colourscale.cpp
  src/gui/render/colourscale.h
  src/gui/render/primitive.cpp
  src/gui/render/primitive.h
Labels: 2

#671 Remove Array 3 (Isotopes)
  src/classes/atomtypedata.cpp
  src/classes/atomtypedata.h
  src/classes/atomtypelist.cpp
  src/classes/atomtypelist.h
  src/classes/isotopedata.cpp
  src/classes/isotopedata.h
  src/classes/isotopologue.cpp
  src/classes/isotopologue.h
  src/classes/neutronweights.cpp
  src/classes/species.cpp
  src/classes/species_io.cpp
  src/data/isotopes.cpp
  src/data/isotopes.h
  src/gui/delegates/isotopecombo.hui
  src/gui/delegates/isotopecombo_funcs.cpp
  src/gui/speciestab.h
  src/gui/speciestab_isotopologues.cpp
  tests/restart/benzene.txt.restart.test
  unit/gui/test_datamanager.cpp
Labels: 4

#684 Const Species
  src/classes/CMakeLists.txt
  src/classes/configuration.h
  src/classes/configuration_contents.cpp
  src/classes/species.cpp
  src/classes/species.h
  src/classes/species_atomic.cpp
  src/classes/species_intra.cpp
  src/classes/speciesangle.cpp
  src/classes/speciesangle.h
  src/classes/speciesatom.cpp
  src/classes/speciesatom.h
  src/classes/speciesimproper.cpp
  src/classes/speciesimproper.h
  src/classes/speciesinfo.cpp
  src/classes/speciesinfo.h
  src/classes/speciestorsion.cpp
  src/classes/speciestorsion.h
  src/classes/xrayweights.cpp
  src/classes/xrayweights.h
  src/gui/delegates/CMakeLists.txt
  src/gui/delegates/usedspeciescombo.hui
  src/gui/delegates/usedspeciescombo_funcs.cpp
  src/gui/keywordwidgets/isotopologueset_funcs.cpp
  src/keywords/species.cpp
  src/keywords/species.h
  src/main/objects.cpp
  src/main/simulation.cpp
  src/modules/checkspecies/checkspecies.h
  src/modules/checkspecies/process.cpp
  src/modules/intrashake/process.cpp
  src/modules/neutronsq/functions.cpp
  src/modules/rdf/functions.cpp
  src/modules/xraysq/functions.cpp
  src/procedure/nodes/addspecies.cpp
  src/procedure/nodes/addspecies.h
Labels: 2

#691 Bugfix 18/05/21 Benchmarks and Const
  benchmark/energy/energy_benchmark.cpp
  src/classes/configuration.h
  src/classes/configuration_contents.cpp
  src/classes/energykernel.cpp
  src/classes/energykernel.h
  src/modules/energy/energy.h
  src/modules/energy/functions.cpp
Labels: 1

#687 Periodic Species
  src/classes/box.cpp
  src/classes/box.h
  src/classes/box_cubic.cpp
  src/classes/box_monoclinic.cpp
  src/classes/box_nonperiodic.cpp
  src/classes/box_orthorhombic.cpp
  src/classes/box_triclinic.cpp
  src/classes/cellarray.cpp
  src/classes/configuration.cpp
  src/classes/configuration.h
  src/classes/configuration_box.cpp
  src/classes/configuration_contents.cpp
  src/classes/configuration_io.cpp
  src/classes/species.cpp
  src/classes/species.h
  src/classes/species_intra.cpp
  src/classes/species_io.cpp
  src/data/elementcolours.cpp
  src/data/elementcolours.h
  src/gui/gui.h
  src/gui/gui.ui
  src/gui/menu_configuration.cpp
  src/gui/models/CMakeLists.txt
  src/gui/models/speciesFilterProxy.cpp
  src/gui/models/speciesFilterProxy.h
  src/gui/models/speciesModel.cpp
  src/gui/models/speciesModel.h
  src/gui/render/primitiveassembly.cpp
  src/gui/render/primitiveassembly.h
  src/gui/render/renderableconfiguration.cpp
  src/gui/render/renderableconfiguration.h
  src/gui/render/renderablespecies.cpp
  src/gui/render/renderablespecies.h
  src/gui/selectspeciesdialog.h
  src/gui/selectspeciesdialog_funcs.cpp
  src/gui/selectspecieswidget.h
  src/gui/selectspecieswidget.ui
  src/gui/selectspecieswidget_funcs.cpp
  src/io/export/coordinates.cpp
  src/procedure/nodes/addspecies.cpp
  src/procedure/nodes/addspecies.h
  src/procedure/nodes/box.cpp
Labels: 4

#688 Updating SpeciesRefList
  src/classes/regionaldistributor.cpp
  src/classes/regionaldistributor.h
  src/gui/keywordwidgets/CMakeLists.txt
  src/gui/keywordwidgets/fileandformat_funcs.cpp
  src/gui/keywordwidgets/function1d_funcs.cpp
  src/gui/keywordwidgets/isotopologueset_funcs.cpp
  src/gui/keywordwidgets/modulegroups_funcs.cpp
  src/gui/keywordwidgets/range_funcs.cpp
  src/gui/keywordwidgets/speciesreflist_funcs.cpp
  src/gui/keywordwidgets/speciessite_funcs.cpp
  src/gui/keywordwidgets/speciessitereflist_funcs.cpp
  src/gui/keywordwidgets/speciesvector.h
  src/gui/keywordwidgets/speciesvector.ui
  src/gui/keywordwidgets/speciesvector_funcs.cpp
  src/gui/keywordwidgets/widget_funcs.cpp
  src/gui/keywordwidgets/widgets.h
  src/gui/models/speciesModel.cpp
  src/gui/models/speciesModel.h
  src/io/import/data1d.cpp
  src/io/import/data2d_cartesian.cpp
  src/keywords/CMakeLists.txt
  src/keywords/base.cpp
  src/keywords/base.h
  src/keywords/enumoptions.h
  src/keywords/geometrylist.cpp
  src/keywords/list.cpp
  src/keywords/list.h
  src/keywords/nodevalueenumoptions.h
  src/keywords/speciesreflist.cpp
  src/keywords/speciesvector.cpp
  src/keywords/speciesvector.h
  src/keywords/types.h
  src/keywords/vec3nodevalue.cpp
  src/keywords/vector_intdouble.cpp
  src/keywords/vector_intstring.cpp
  src/keywords/vector_stringpair.cpp
  src/module/module.cpp
  src/modules/atomshake/process.cpp
  src/modules/benchmark/process.cpp
  src/modules/calculate_cn/process.cpp
  src/modules/checkspecies/process.cpp
  src/modules/energy/process.cpp
  src/modules/forces/forces.h
  src/modules/forces/functions.cpp
  src/modules/intrashake/process.cpp
  src/modules/md/init.cpp
  src/modules/md/md.h
  src/modules/md/process.cpp
  src/modules/molshake/init.cpp
  src/modules/molshake/process.cpp
  web/content/docs/modules/evolution/molshake/_index.md
Labels: 2

#692 Show all parameters in a single cell
  src/gui/models/CMakeLists.txt
  src/gui/models/speciesAngleModel.cpp
  src/gui/models/speciesBondModel.cpp
  src/gui/models/speciesImproperModel.cpp
  src/gui/models/speciesModelUtils.cpp
  src/gui/models/speciesModelUtils.h
  src/gui/models/speciesTorsionModel.cpp
  src/templates/algorithms.h
  unit/gui/test_speciestab.cpp
Labels: 2

#693 Box Regions
  src/classes/configuration.h
  src/classes/configuration_box.cpp
  src/classes/configuration_contents.cpp
  src/procedure/nodes/CMakeLists.txt
  src/procedure/nodes/addspecies.cpp
  src/procedure/nodes/addspecies.h
  src/procedure/nodes/generalregion.cpp
  src/procedure/nodes/generalregion.h
  src/procedure/nodes/node.cpp
  src/procedure/nodes/node.h
  src/procedure/nodes/nodes.h
  src/procedure/nodes/regionbase.cpp
  src/procedure/nodes/regionbase.h
  src/procedure/nodes/sequence.cpp
  web/content/docs/procedures/nodes/addspeciesnode.md
  web/content/docs/procedures/nodes/generalregion.md
  web/content/docs/reference/positioningtype.md
Labels: 4

#698 Bugfix 24-05-21 Warnings and Configuration Generation
  src/classes/distributor.cpp
  src/classes/energykernel.cpp
  src/classes/forcekernel.cpp
  src/classes/moleculedistributor.cpp
  src/data/isotopes.cpp
  src/gui/importforcefieldwizard_funcs.cpp
  src/gui/menu_configuration.cpp
  src/gui/models/dataManagerSimulationModel.cpp
  src/gui/models/speciesAngleModel.cpp
  src/gui/models/speciesAtomModel.cpp
  src/gui/models/speciesBondModel.cpp
  src/gui/models/speciesImproperModel.cpp
  src/gui/models/speciesTorsionModel.cpp
  src/gui/models/xmlAtomModel.cpp
  src/gui/models/xmlImproperModel.cpp
  src/gui/models/xmlTorsionModel.cpp
  src/main/keywords_configuration.cpp
  src/math/error.cpp
  src/modules/rdf/functions.cpp
  src/procedure/nodes/node.cpp
  unit/test_sampledvalues.cpp
Labels: 1

#700 Energy Optimisation
  src/classes/energykernel.cpp
Labels: 1

#699 Import LigParGen
  src/classes/atomtype.cpp
  src/classes/atomtype.h
  src/classes/coredata.cpp
  src/classes/coredata.h
  src/classes/species.cpp
  src/classes/species.h
  src/classes/species_atomic.cpp
  src/classes/species_intra.cpp
  src/data/ff/ff.cpp
  src/data/ff/ff.h
  src/gui/CMakeLists.txt
  src/gui/addforcefieldtermsdialog.h
  src/gui/addforcefieldtermsdialog_funcs.cpp
  src/gui/gui.h
  src/gui/gui.ui
  src/gui/gui_funcs.cpp
  src/gui/importforcefieldwizard.h
  src/gui/importforcefieldwizard.ui
  src/gui/importforcefieldwizard_funcs.cpp
  src/gui/importligpargendialog.h
  src/gui/importligpargendialog.ui
  src/gui/importligpargendialog_funcs.cpp
  src/gui/menu_species.cpp
  src/main/dissolve.h
  src/main/species.cpp
Labels: 4
