Repository disorderedmaterials/dissolve, pull requests merged in 2022-05, with the labels that each got.

#1034 Desensitize
  src/gui/charts/chart.hui
  src/gui/charts/chart_funcs.cpp
  src/gui/charts/chartblock.h
  src/gui/charts/procedurenode.h
  src/gui/charts/procedurenode_funcs.cpp
  src/gui/configurationtab.h
  src/gui/configurationtab_funcs.cpp
  src/gui/forcefieldtab.h
  src/gui/forcefieldtab_funcs.cpp
  src/gui/gizmo.h
  src/gui/graphgizmo.h
  src/gui/graphgizmo_funcs.cpp
  src/gui/gui.h
  src/gui/gui_simulation.cpp
  src/gui/integrator1dgizmo.h
  src/gui/integrator1dgizmo_funcs.cpp
  src/gui/layertab.h
  src/gui/layertab_funcs.cpp
  src/gui/maintab.h
  src/gui/maintabswidget.hui
  src/gui/maintabswidget_funcs.cpp
  src/gui/menu_simulation.cpp
  src/gui/messagestab.h
  src/gui/messagestab_funcs.cpp
  src/gui/modulecontrolwidget.h
  src/gui/modulecontrolwidget_funcs.cpp
  src/gui/speciestab.h
  src/gui/speciestab_funcs.cpp
  src/gui/workspacetab.h
  src/gui/workspacetab_funcs.cpp
  src/modules/widget.cpp
  src/modules/widget.h
Labels: 1

#1037 Fix Benchmarks
  src/base/processpool.cpp
Labels: 1

#1040 Restart File UX
  src/dissolve-gui.cpp
  src/gui/CMakeLists.txt
  src/gui/gui.h
  src/gui/gui.ui
  src/gui/gui_funcs.cpp
  src/gui/gui_simulation.cpp
  src/gui/menu_file.cpp
  src/gui/menu_simulation.cpp
  src/gui/selectrestartfiledialog.h
  src/gui/selectrestartfiledialog.ui
  src/gui/selectrestartfiledialog_funcs.cpp
Labels: 4

#1049 Clear additional potentials
  src/gui/gui.h
  src/gui/gui.ui
  src/gui/menu_simulation.cpp
  src/main/dissolve.h
  src/main/pairpotentials.cpp
Labels: 2

#1042 Remove Workspaces
  src/gui/CMakeLists.txt
  src/gui/dataviewer_contextmenu.cpp
  src/gui/datawidget.h
  src/gui/datawidget.ui
  src/gui/datawidget_funcs.cpp
  src/gui/getgizmonamedialog.h
  src/gui/getgizmonamedialog.ui
  src/gui/getgizmonamedialog_funcs.cpp
  src/gui/gettabnamedialog_funcs.cpp
  src/gui/gizmo.cpp
  src/gui/gizmo.h
  src/gui/gizmos.h
  src/gui/graphgizmo.h
  src/gui/graphgizmo.ui
  src/gui/graphgizmo_funcs.cpp
  src/gui/gui.h
  src/gui/gui.ui
  src/gui/gui_funcs.cpp
  src/gui/integrator1dgizmo.h
  src/gui/integrator1dgizmo.ui
  src/gui/integrator1dgizmo_funcs.cpp
  src/gui/maintab.cpp
  src/gui/maintab.h
  src/gui/maintabswidget.hui
  src/gui/maintabswidget_funcs.cpp
  src/gui/menu_workspace.cpp
  src/gui/viewer.hui
  src/gui/viewer_view.cpp
  src/gui/workspacetab.h
  src/gui/workspacetab.ui
  src/gui/workspacetab_funcs.cpp
Labels: 2

#1048 Keep CellArrays consistent with pair potential range
  src/classes/configuration.h
  src/classes/configuration_box.cpp
  src/classes/configuration_io.cpp
  src/main/io.cpp
  src/main/simulation.cpp
Labels: 2

#1051 Patch 05 2022
  src/classes/atom.cpp
  src/classes/cell.cpp
  src/classes/cell.h
  src/classes/cellarray.cpp
  src/classes/cellarray.h
  src/classes/configuration.h
  src/classes/configuration_box.cpp
  src/classes/configuration_upkeep.cpp
  src/classes/species_atomic.cpp
  src/gui/datawidget_funcs.cpp
  src/gui/gui.h
  src/gui/gui.ui
  src/gui/gui_funcs.cpp
  src/gui/gui_simulation.cpp
  src/gui/icons/general_clear.svg
  src/gui/icons/general_output.svg
  src/gui/icons/tabs_layer.svg
  src/gui/icons/tabs_layer_disabled.svg
  src/gui/keywordwidgets/configuration.h
  src/gui/keywordwidgets/configuration.ui
  src/gui/keywordwidgets/configuration_funcs.cpp
  src/gui/keywordwidgets/module.h
  src/gui/keywordwidgets/module.ui
  src/gui/keywordwidgets/module_funcs.cpp
  src/gui/keywordwidgets/node.h
  src/gui/keywordwidgets/node.ui
  src/gui/keywordwidgets/node_funcs.cpp
  src/gui/keywordwidgets/species.h
  src/gui/keywordwidgets/species.ui
  src/gui/keywordwidgets/species_funcs.cpp
  src/gui/layertab.ui
  src/gui/layertab_funcs.cpp
  src/gui/main.qrc
  src/gui/maintabswidget_funcs.cpp
  src/gui/menu_file.cpp
  src/gui/menu_simulation.cpp
  src/gui/models/speciesIsoModel.cpp
  src/gui/render/colourscale.cpp
  src/gui/render/renderabledata2d.cpp
  src/modules/bragg/bragg.h
  src/modules/bragg/process.cpp
  src/modules/calculate_axisangle/gui/calculateaxisanglewidget_funcs.cpp
  src/modules/calculate_dangle/gui/calculatedanglewidget_funcs.cpp
  src/modules/epsr/epsr.h
  src/modules/import_trajectory/process.cpp
  src/modules/md/md.cpp
  src/modules/md/md.h
  src/modules/md/process.cpp
  unit/classes/cells.cpp
  unit/gui/speciestab.cpp
Labels: 2

#1052 1046 toml cleanup
  src/base/serialiser.h
  src/classes/atomtype.cpp
  src/classes/atomtype.h
  src/classes/box.cpp
  src/classes/box.h
  src/classes/configuration.cpp
  src/classes/configuration.h
  src/classes/isotopologue.cpp
  src/classes/isotopologue.h
  src/classes/serializablepairpotential.cpp
  src/classes/serializablepairpotential.h
  src/classes/species.cpp
  src/classes/species.h
  src/classes/speciesangle.cpp
  src/classes/speciesangle.h
  src/classes/speciesatom.cpp
  src/classes/speciesatom.h
  src/classes/speciesbond.cpp
  src/classes/speciesbond.h
  src/classes/speciesimproper.cpp
  src/classes/speciesimproper.h
  src/classes/speciessite.cpp
  src/classes/speciessite.h
  src/classes/speciestorsion.cpp
  src/classes/speciestorsion.h
  src/main/dissolve.h
  src/main/io.cpp
  src/main/species.cpp
Labels: 4

#1058 Overcome Flat Geometries in Minimiser
  src/classes/species.h
  src/classes/species_atomic.cpp
  src/gui/specieseditor_funcs.cpp
  src/gui/specieswidget_funcs.cpp
Labels: 2

#1060 Manual Procedure Creation
  src/gui/menu_configuration.cpp
  src/keywords/nodevector.h
  src/keywords/store.cpp
  src/modules/calculate_angle/angle.cpp
  src/modules/calculate_angle/process.cpp
  src/modules/calculate_axisangle/axisangle.cpp
  src/modules/calculate_axisangle/process.cpp
  src/modules/calculate_cn/cn.cpp
  src/modules/calculate_cn/process.cpp
  src/modules/calculate_dangle/dangle.cpp
  src/modules/calculate_dangle/process.cpp
  src/modules/calculate_rdf/rdf.cpp
  src/modules/calculate_sdf/process.cpp
  src/modules/calculate_sdf/sdf.cpp
  src/procedure/nodes/CMakeLists.txt
  src/procedure/nodes/aliases.h
  src/procedure/nodes/node.cpp
  src/procedure/nodes/node.h
  src/procedure/nodes/operatenumberdensitynormalise.cpp
  src/procedure/nodes/operatenumberdensitynormalise.h
  src/procedure/nodes/operatesitepopulationnormalise.cpp
  src/procedure/nodes/operatesitepopulationnormalise.h
  src/procedure/nodes/registry.cpp
  src/procedure/nodes/registry.h
  src/procedure/nodes/select.cpp
  src/procedure/nodes/select.h
  src/procedure/nodes/sequence.cpp
  src/procedure/nodes/sequence.h
  src/procedure/procedure.cpp
  src/procedure/procedure.h
  tests/calculate_dangle/dangle.txt
  unit/gui/expressionVariableVectorModel.cpp
  unit/gui/procedure.cpp
Labels: 8

#1064 Symmetrise angle
  src/modules/calculate_angle/angle.cpp
  src/modules/calculate_angle/angle.h
  src/modules/calculate_angle/process.cpp
  src/modules/calculate_axisangle/axisangle.cpp
  src/modules/calculate_axisangle/axisangle.h
  src/modules/calculate_axisangle/process.cpp
  src/modules/calculate_dangle/dangle.cpp
  src/modules/calculate_dangle/dangle.h
  src/modules/calculate_dangle/process.cpp
  src/procedure/nodes/calculateangle.cpp
  src/procedure/nodes/calculateangle.h
  src/procedure/nodes/operateexpression.cpp
  src/procedure/nodes/operateexpression.h
  src/procedure/nodes/parameters.cpp
  src/procedure/nodes/parameters.h
Labels: 4

#1066 Manage master terms
  src/base/sysfunc.h
  src/classes/coredata.cpp
  src/classes/coredata.h
  src/classes/species.h
  src/classes/species_intra.cpp
  src/classes/species_io.cpp
  src/classes/species_isotopologues.cpp
  src/gui/forcefieldtab_funcs.cpp
  src/gui/menu_layer.cpp
  src/gui/menu_species.cpp
  src/gui/models/moduleLayerModel.cpp
  src/main/dissolve.h
  src/main/layers.cpp
  src/main/species.cpp
  src/module/module.cpp
  src/module/module.h
  src/modules/registry.cpp
  unit/algorithms/sysFunc.cpp
Labels: 4

#1067 Patch 05/22 Part 3
  src/data/ff/oplsaa2005/intramolecular.cpp
  src/gui/configurationtab_funcs.cpp
  src/gui/keywordwidgets/node_funcs.cpp
  src/gui/keywordwidgets/nodeandinteger_funcs.cpp
  src/keywords/node.h
  src/keywords/nodeandinteger.h
  src/modules/calculate_sdf/gui/calculatesdfwidget_funcs.cpp
  src/modules/energy/gui/energywidget_funcs.cpp
  src/modules/rdf/gui/rdfwidget.h
  src/modules/rdf/gui/rdfwidget_funcs.cpp
Labels: 2

#1070 Legacy Restart Data Deserialisation
  src/classes/partialset.cpp
  src/genericitems/CMakeLists.txt
  src/genericitems/deserialisers.cpp
  src/genericitems/deserialisers.h
  src/genericitems/legacy.cpp
  src/genericitems/legacy.h
  src/genericitems/list.cpp
  src/genericitems/list.h
  src/genericitems/producers.cpp
  src/main/io.cpp
  src/main/version.cpp
  src/main/version.h
Labels: 4

#1081 Pure MD Layer
  src/gui/gui.h
  src/gui/gui.ui
  src/gui/menu_layer.cpp
Labels: 2

#1082 Improved CIF Import
  src/classes/species.cpp
  src/classes/species.h
  src/classes/species_intra.cpp
  src/classes/speciessite.cpp
  src/data/elements.cpp
  src/data/elements.h
  src/gui/importcifdialog.h
  src/gui/importcifdialog.ui
  src/gui/importcifdialog_funcs.cpp
  src/gui/models/cifAssemblyModel.cpp
  src/io/import/CIFImportLexer.g4
  src/io/import/cif.cpp
  src/io/import/cifclasses.cpp
  src/io/import/cifclasses.h
Labels: 8

#1085 Data Mutation Fixes
  src/classes/speciessite.cpp
  src/gui/gui_simulation.cpp
  src/gui/keywordwidgets/isotopologueset_funcs.cpp
  src/gui/layertab_funcs.cpp
  src/gui/modulecontrolwidget.h
  src/gui/modulecontrolwidget_funcs.cpp
  src/gui/signals.h
  src/gui/speciestab_isotopologues.cpp
  src/main/species.cpp
Labels: 4

#1080 Const correctness of deserialiser
  src/base/serialiser.h
  src/classes/coredata.h
  src/classes/isotopologue.cpp
  src/classes/isotopologue.h
  src/classes/masters.cpp
  src/classes/serializablepairpotential.cpp
  src/classes/serializablepairpotential.h
  src/classes/species.cpp
  src/classes/species.h
  src/classes/speciesangle.cpp
  src/classes/speciesangle.h
  src/classes/speciesatom.cpp
  src/classes/speciesatom.h
  src/classes/speciesbond.cpp
  src/classes/speciesbond.h
  src/classes/speciesimproper.cpp
  src/classes/speciesimproper.h
  src/classes/speciesintra.h
  src/classes/speciessite.cpp
  src/classes/speciessite.h
  src/classes/speciestorsion.cpp
  src/classes/speciestorsion.h
  src/main/dissolve.h
  src/main/io.cpp
  src/procedure/nodevalue.cpp
  src/procedure/nodevalue.h
  src/templates/vector3.h
  unit/io/toml.cpp
Labels: 8, TOML

#1088 Cu-BTC Forcefield (Zhao 2010)
  src/classes/speciesbond.cpp
  src/classes/speciesbond.h
  src/data/ff/ff.cpp
  src/data/ff/ff.h
  src/data/ff/library.cpp
  src/data/ff/uff/uff.cpp
  src/data/ff/uff/uff.h
  src/data/ff/zhao2010/CMakeLists.txt
  src/data/ff/zhao2010/zhao2010.cpp
  src/data/ff/zhao2010/zhao2010.h
Labels: 4

#1093 Mutable AtomType names
  src/gui/addforcefieldtermsdialog_funcs.cpp
  src/gui/forcefieldtab_funcs.cpp
  src/gui/keywordwidgets/atomtypevector_funcs.cpp
  src/gui/models/atomTypeModel.cpp
  src/gui/models/atomTypeModel.h
  src/gui/selectatomtypedialog_funcs.cpp
  src/gui/selectatomtypewidget.h
  src/gui/selectatomtypewidget_funcs.cpp
Labels: 4
