Repository disorderedmaterials/dissolve, pull requests merged in 2022-06, with the labels that each got.

#1094 Isotopologues Context Menu
  src/classes/isotopologue.cpp
  src/classes/isotopologue.h
  src/gui/models/speciesIsoModel.cpp
  src/gui/speciestab.h
  src/gui/speciestab.ui
  src/gui/speciestab_isotopologues.cpp
Labels: 4

#1098 Patch - June 2022, Part 1
  src/gui/CMakeLists.txt
  src/gui/gui.h
  src/gui/gui.ui
  src/gui/layertab.h
  src/gui/layertab.ui
  src/gui/layertab_funcs.cpp
  src/gui/maintabsbar_funcs.cpp
  src/gui/maintabswidget.hui
  src/gui/maintabswidget_funcs.cpp
  src/gui/menu_species.cpp
  src/gui/models/moduleLayerModel.cpp
  src/gui/modulecontrolwidget.h
  src/gui/modulecontrolwidget.ui
  src/gui/modulecontrolwidget_funcs.cpp
  src/gui/tmdiarea.hui
  src/gui/tmdiarea_funcs.cpp
Labels: 2

#1099 Configuration & PairPotentials
  src/classes/pairpotential.cpp
  src/gui/forcefieldtab.h
  src/gui/forcefieldtab_funcs.cpp
  src/gui/maintabswidget.hui
  src/gui/maintabswidget_funcs.cpp
  src/gui/menu_simulation.cpp
  src/gui/models/pairPotentialModel.cpp
  src/main/dissolve.cpp
  src/main/dissolve.h
  src/main/io.cpp
  src/main/pairpotentials.cpp
  src/main/simulation.cpp
  unit/gui/forcefieldTab.cpp
Labels: 4

#1101 Harbor Release fix
  .azure-pipelines/templates/push-harbor.yml
  ci/windows/dissolve-gui.iss
Labels: Scope: CI, 2, Priority: High

#1079 Move ANTLR to where macqtdeploy can find it
  .azure-pipelines/templates/package-osx.yml
  conanfile.txt
Labels: Only: OSX, Scope: CI, Priority: High

#1103 Patch - June 2022, Part 2
  src/classes/atomtype.cpp
  src/classes/partialset.cpp
  src/genericitems/list.cpp
  src/genericitems/list.h
  src/gui/configurationtab.h
  src/gui/configurationtab.ui
  src/gui/configurationtab_funcs.cpp
  src/gui/gui_funcs.cpp
  src/main/dissolve.cpp
  src/main/dissolve.h
  src/main/pairpotentials.cpp
  src/modules/md/process.cpp
Labels: 2

#1104 Try and deploy conan dependencies on Windows
  .azure-pipelines/templates/package-windows.yml
  ci/windows/dissolve-gui.iss
Labels: Type: Bug, Only: Windows, Scope: CI

#1123 Docs Update - June 22
  web/content/docs/procedures/nodes/addnode.md
  web/content/docs/procedures/nodes/coordinatesetsnode.md
  web/content/docs/procedures/nodes/operatenumberdensitynormalisenode.md
  web/content/docs/reference/boxactionstyle.md
  web/content/docs/reference/coordinatesetsource.md
  web/content/docs/reference/positioningtype.md
  web/content/docs/reference/selectionpopulation.md
  web/content/examples/_index.md
  web/content/examples/argon/icon.png
  web/content/examples/argon/icon.svg
  web/content/examples/argon/step2.md
  web/content/examples/benzene/icon.png
  web/content/examples/benzene/step1.md
  web/content/examples/cu-btc/icon.png
  web/content/examples/cu-btc/step1.md
  web/content/examples/cu-btc/step2.md
  web/content/examples/cu-btc/step5.md
  web/content/examples/emim-oac/exercise1.md
  web/content/examples/emim-oac/exercises.md
  web/content/examples/emim-oac/icon.png
  web/content/examples/emim-oac/step2.md
  web/content/examples/emim-oac/step9.md
  web/content/examples/silica/icon.png
  web/content/examples/water/epsrmodule-totalgr.png
  web/content/examples/water/icon.png
  web/content/examples/water/icon.svg
  web/content/examples/water/step1a.md
  web/content/examples/water/step2.md
  web/content/examples/water/step7.md
  web/content/packages.md
  web/layouts/shortcodes/cimage.html
Labels: 4

#1134 Docs Hotfix - June 2022, Part 2
  web/content/examples/ligpargen/_index.md
Labels: 1

#1144 Fix Add/CoordinateSets node crash
  src/gui/menu_configuration.cpp
  src/procedure/nodes/add.cpp
  src/procedure/nodes/add.h
Labels: 2

#1150 AvgMol - Check for data arrays
  src/modules/calculate_avgmol/functions.cpp
Labels: 1
