Repository disorderedmaterials/dissolve, pull requests merged in 2022-03, with the labels that each got.

#977 Bugfix 28/2/22 Add Layer Crash
  .azure-pipelines/continuous.yml
  .azure-pipelines/pr.yml
  .azure-pipelines/release.yml
  src/gui/menu_layer.cpp
  src/main/configurations.cpp
  src/main/dissolve.h
Labels: 1

#981 Update linux to new builds
  web/content/packages.md
Labels: 4

#975 Check at start of RDF run for size factor issues
  src/modules/rdf/process.cpp
Labels: 4

#969 Qt6.2.2
  .azure-pipelines/pr.yml
  .azure-pipelines/templates/build-osx.yml
  .azure-pipelines/templates/build-windows.yml
  .azure-pipelines/templates/package-osx.yml
  .azure-pipelines/templates/package-windows.yml
  CMakeLists.txt
  flake.nix
  nix/qt6.nix
  src/gui/charts/CMakeLists.txt
  src/gui/delegates/CMakeLists.txt
  src/gui/keywordwidgets/CMakeLists.txt
  src/gui/models/CMakeLists.txt
  src/gui/render/CMakeLists.txt
  src/gui/widgets/CMakeLists.txt
  src/modules/CMakeLists.txt
Labels: 16

#982 Update isotopologues when changing atom types in the GUI
  src/gui/models/speciesAtomModel.cpp
  src/gui/models/speciesAtomModel.h
  src/gui/speciestab_funcs.cpp
  unit/gui/speciestab.cpp
Labels: 4

#987 MC Tidy
  src/math/gaussfit.cpp
  src/math/gaussfit.h
  src/math/mc.cpp
  src/math/mc.h
  src/math/poissonfit.cpp
  src/math/poissonfit.h
  src/modules/epsr/process.cpp
  src/procedure/nodes/fit1d.cpp
Labels: 4

#988 Partial Totals
  src/classes/partialset.cpp
  src/classes/partialset.h
  src/math/histogram1d.cpp
  src/math/histogram1d.h
  src/modules/epsr/process.cpp
  src/modules/neutronsq/functions.cpp
  src/modules/neutronsq/gui/neutronsqwidget_funcs.cpp
  src/modules/rdf/functions.cpp
  src/modules/sq/functions.cpp
  src/modules/sq/process.cpp
  src/modules/xraysq/functions.cpp
  src/modules/xraysq/gui/xraysqwidget_funcs.cpp
  tests/restart/benzene.txt
  tests/restart/benzene.txt.restart.test
Labels: 4

#991 CMake include dirs
  CMakeLists.txt
  nix/patches/no-conan.patch
  src/base/CMakeLists.txt
  src/classes/CMakeLists.txt
  src/data/CMakeLists.txt
  src/data/ff/CMakeLists.txt
  src/data/sginfo/CMakeLists.txt
  src/genericitems/CMakeLists.txt
  src/gui/models/CMakeLists.txt
  src/io/CMakeLists.txt
  src/io/export/CMakeLists.txt
  src/io/import/CMakeLists.txt
  src/keywords/CMakeLists.txt
  src/main/CMakeLists.txt
  src/math/CMakeLists.txt
  src/module/CMakeLists.txt
  src/modules/CMakeLists.txt
  src/procedure/CMakeLists.txt
  src/procedure/nodes/CMakeLists.txt
Labels: 1

#974 Module layer context menu
  src/base/sysfunc.cpp
  src/base/sysfunc.h
  src/genericitems/list.cpp
  src/genericitems/list.h
  src/gui/layertab.h
  src/gui/layertab.ui
  src/gui/layertab_funcs.cpp
  src/gui/models/moduleLayerModel.cpp
  src/gui/models/moduleLayerModel.h
  src/gui/modulecontrolwidget.h
  src/gui/modulecontrolwidget_funcs.cpp
  src/modules/accumulate/gui/accumulatewidget.h
  src/modules/accumulate/gui/accumulatewidget_funcs.cpp
  src/modules/bragg/gui/braggwidget.h
  src/modules/bragg/gui/braggwidget_funcs.cpp
  src/modules/calculate_angle/gui/calculateanglewidget.h
  src/modules/calculate_angle/gui/calculateanglewidget_funcs.cpp
  src/modules/calculate_axisangle/gui/calculateaxisanglewidget.h
  src/modules/calculate_axisangle/gui/calculateaxisanglewidget_funcs.cpp
  src/modules/calculate_cn/gui/calculatecnwidget.h
  src/modules/calculate_cn/gui/calculatecnwidget_funcs.cpp
  src/modules/calculate_dangle/gui/calculatedanglewidget.h
  src/modules/calculate_dangle/gui/calculatedanglewidget_funcs.cpp
  src/modules/calculate_rdf/gui/calculaterdfwidget.h
  src/modules/calculate_rdf/gui/calculaterdfwidget_funcs.cpp
  src/modules/calculate_sdf/gui/calculatesdfwidget.h
  src/modules/calculate_sdf/gui/calculatesdfwidget_funcs.cpp
  src/modules/energy/gui/energywidget.h
  src/modules/energy/gui/energywidget_funcs.cpp
  src/modules/epsr/gui/epsrwidget.h
  src/modules/epsr/gui/epsrwidget_funcs.cpp
  src/modules/neutronsq/gui/neutronsqwidget.h
  src/modules/neutronsq/gui/neutronsqwidget_funcs.cpp
  src/modules/rdf/gui/rdfwidget.h
  src/modules/rdf/gui/rdfwidget_funcs.cpp
  src/modules/sq/gui/sqwidget.h
  src/modules/sq/gui/sqwidget_funcs.cpp
  src/modules/widget.cpp
  src/modules/widget.h
  src/modules/xraysq/gui/xraysqwidget.h
  src/modules/xraysq/gui/xraysqwidget_funcs.cpp
  unit/algorithms/sysFunc.cpp
Labels: 4

#994 Enable native FileChooser on IDaaS
  flake.nix
Labels: 16

#997 Push to Harbor on release
  .azure-pipelines/templates/create-release.yml
Labels: 2
