Repository disorderedmaterials/dissolve, pull requests merged in 2022-04, with the labels that each got.

#986 Recalculate Bragg reflections after changes to Bragg module
  src/keywords/base.h
  src/modules/bragg/bragg.cpp
  src/modules/bragg/bragg.h
  src/modules/bragg/gui/braggwidget_funcs.cpp
  src/modules/bragg/process.cpp
Labels: 8

#1006 Fix Zhang2013
  src/data/ff/zhang2013/zhang2013.cpp
Labels: 1

#1009 XRay Only Layer
  examples/argon/input.txt
  examples/benzene/input.txt
  examples/silica_bulk/input.txt
  examples/water/input.txt
  src/gui/gui.h
  src/gui/gui.ui
  src/gui/menu_layer.cpp
  src/module/layer.cpp
  src/module/layer.h
  src/module/module.cpp
  src/module/module.h
  src/modules/neutronsq/neutronsq.h
  src/modules/neutronsq/process.cpp
  src/modules/sq/process.cpp
  src/modules/sq/sq.h
  src/modules/xraysq/process.cpp
  src/modules/xraysq/xraysq.h
Labels: 2

#1011 Connect the keyword widget to the setModified slot
  src/gui/configurationtab_funcs.cpp
Labels: 4

#1021 Copy Species From Existing
  src/gui/gui.h
  src/gui/gui.ui
  src/gui/menu_species.cpp
  src/gui/models/speciesFilterProxy.cpp
  src/gui/models/speciesFilterProxy.h
  src/gui/selectspeciesdialog.h
  src/gui/selectspeciesdialog_funcs.cpp
  src/gui/selectspecieswidget.h
  src/gui/selectspecieswidget_funcs.cpp
  unit/classes/flags.cpp
Labels: 2

#1023 Remove ProcedureEditor
  src/gui/CMakeLists.txt
  src/gui/configurationtab.h
  src/gui/configurationtab.ui
  src/gui/configurationtab_funcs.cpp
  src/gui/procedurecontrolstack.cpp
  src/gui/procedurecontrolstack.h
  src/gui/procedureeditor.h
  src/gui/procedureeditor.ui
  src/gui/procedureeditor_funcs.cpp
  src/modules/analyse/gui/analysewidget.ui
  src/modules/analyse/gui/analysewidget_funcs.cpp
Labels: 4

#1004 Coordinate Sets for Species
  benchmark/CMakeLists.txt
  benchmark/forces/forces_benchmark.cpp
  examples/benzene/input.txt
  examples/water/input.txt
  src/classes/configuration.cpp
  src/classes/configuration.h
  src/classes/forcekernel.cpp
  src/classes/forcekernel.h
  src/classes/species.cpp
  src/classes/species.h
  src/classes/species_io.cpp
  src/gui/configurationtab_funcs.cpp
  src/gui/keywordwidgets/nodevalueenumoptions.h
  src/gui/keywordwidgets/nodevalueenumoptions_funcs.cpp
  src/gui/keywordwidgets/species_funcs.cpp
  src/gui/keywordwidgets/vec3nodevalue_funcs.cpp
  src/gui/menu_configuration.cpp
  src/keywords/species.cpp
  src/keywords/store.cpp
  src/main/io.cpp
  src/modules/benchmark/process.cpp
  src/modules/forces/forces.h
  src/modules/forces/functions.cpp
  src/modules/md/functions.cpp
  src/modules/md/md.h
  src/procedure/nodes/CMakeLists.txt
  src/procedure/nodes/add.cpp
  src/procedure/nodes/add.h
  src/procedure/nodes/context.cpp
  src/procedure/nodes/context.h
  src/procedure/nodes/coordinatesets.cpp
  src/procedure/nodes/coordinatesets.h
  src/procedure/nodes/node.cpp
  src/procedure/nodes/node.h
  src/procedure/nodes/nodes.h
  src/procedure/nodes/sequence.cpp
Labels: 8
