Repository disorderedmaterials/dissolve, pull requests merged in 2022-08, with the labels that each got.

#1207 1196 Refer to new Add Configuration Wizard in examples
  web/content/examples/argon/step3.md
  web/content/examples/benzene/step2.md
  web/content/examples/cu-btc/step3.md
  web/content/examples/emim-oac/step4.md
  web/content/examples/post-processing/step2.md
  web/content/examples/silica/step3.md
  web/content/examples/water/step2.md
Labels: 2

#1203 Patch 07/22
  src/classes/partialset.cpp
  src/genericitems/list.cpp
  src/gui/addconfigurationdialog.ui
  src/gui/addconfigurationdialog_funcs.cpp
  src/gui/importligpargendialog.h
  src/gui/importligpargendialog_funcs.cpp
  src/gui/maintabswidget_funcs.cpp
  src/main/simulation.cpp
  src/module/layer.cpp
  src/module/layer.h
  src/modules/rdf/process.cpp
  src/modules/rdf/rdf.cpp
  src/modules/rdf/rdf.h
  web/content/docs/modules/correlation/rdf/_index.md
Labels: 4

#1208 Fix intrashake energy
  benchmark/energy/energy_benchmark.cpp
  src/classes/energykernel.cpp
  src/classes/energykernel.h
  src/modules/energy/process.cpp
  src/modules/intrashake/process.cpp
  src/modules/molshake/process.cpp
Labels: 2

#1183 Clarify PairPotential Charges
  src/classes/pairpotential.cpp
  src/classes/pairpotential.h
  src/main/pairpotentials.cpp
  unit/classes/cells.cpp
  unit/math/geometryMin.cpp
Labels: 1

#1210 Remove TableWidgetUpdater
  src/gui/datamanagerdialog_funcs.cpp
  src/gui/forcefieldtab_funcs.cpp
  src/gui/helpers/tablewidgetupdater.h
  src/gui/speciestab_geometry.cpp
Labels: 1

#1192 POD Keyword Limits
  src/gui/keywordwidgets/double_funcs.cpp
  src/gui/keywordwidgets/integer_funcs.cpp
  src/gui/keywordwidgets/optionaldouble_funcs.cpp
  src/gui/keywordwidgets/optionalint_funcs.cpp
  src/gui/keywordwidgets/range_funcs.cpp
  src/gui/keywordwidgets/vec3double_funcs.cpp
  src/gui/keywordwidgets/vec3integer_funcs.cpp
  src/keywords/double.cpp
  src/keywords/double.h
  src/keywords/integer.cpp
  src/keywords/integer.h
  src/keywords/optionaldouble.cpp
  src/keywords/optionaldouble.h
  src/keywords/optionalint.cpp
  src/keywords/optionalint.h
  src/keywords/range.cpp
  src/keywords/range.h
  src/keywords/vec3double.cpp
  src/keywords/vec3double.h
  src/keywords/vec3integer.cpp
  src/keywords/vec3integer.h
  unit/CMakeLists.txt
  unit/gui/CMakeLists.txt
  unit/gui/optionalDoubleKeyword.cpp
  unit/keywords/CMakeLists.txt
  unit/keywords/double.cpp
  unit/keywords/integer.cpp
  unit/keywords/optionalDouble.cpp
  unit/keywords/range.cpp
Labels: 4

#1202 CIF Upgrades
  src/data/elements.cpp
  src/data/spacegroups.cpp
  src/data/spacegroups.h
  src/gui/importcifdialog.h
  src/gui/importcifdialog.ui
  src/gui/importcifdialog_funcs.cpp
  src/io/import/cif.cpp
  src/io/import/cif.h
  unit/classes/CMakeLists.txt
  unit/classes/spacegroups.cpp
Labels: 16

#1209 Add RenderableGroupManager Model
  src/gui/addforcefieldtermsdialog_funcs.cpp
  src/gui/dataviewer_contextmenu.cpp
  src/gui/datawidget.h
  src/gui/datawidget.ui
  src/gui/datawidget_funcs.cpp
  src/gui/helpers/treewidgetupdater.h
  src/gui/importcifdialog_funcs.cpp
  src/gui/importspeciesdialog_funcs.cpp
  src/gui/models/CMakeLists.txt
  src/gui/models/renderableGroupManagerModel.cpp
  src/gui/models/renderableGroupManagerModel.h
Labels: 4

#1180 Procedure Editing - Part 2
  src/gui/modulecontrolwidget.h
  src/gui/modulecontrolwidget.ui
  src/gui/modulecontrolwidget_funcs.cpp
  src/keywords/store.h
Labels: 4

#1212 Include antlr4 in Windows installer
  ci/windows/dissolve-gui.iss
Labels: Type: Bug, Only: Windows, Scope: CI, 1, Priority: High

#1213 Splash Image 1.0
  icon/splash.svg
  src/gui/gui.ui
  src/gui/icons/simple.png
  src/gui/icons/splash.png
  src/gui/images/big.png
  src/gui/images/cornerhexagons.png
  src/gui/images/hexagons1.jpg
  src/gui/images/hexagons1.png
  src/gui/images/squares.jpg
  src/gui/main.qrc
Labels: 1

#1211 1162 AtomShake Fail
  src/main.cpp
Labels: 1

#1182 Procedure Editing - Part 3
  src/classes/configuration.cpp
  src/gui/models/isotopologueSetModel.cpp
  src/gui/models/isotopologueSetModel.h
  src/gui/models/procedureModel.cpp
  src/gui/models/procedureModel.h
  src/gui/procedurewidget.h
  src/gui/procedurewidget.ui
  src/gui/procedurewidget_funcs.cpp
  src/keywords/dynamicsitenodes.cpp
  src/keywords/nodebranch.cpp
  src/keywords/procedure.cpp
  src/main/io.cpp
  src/modules/analyse/analyse.cpp
  src/procedure/nodes/collect1d.cpp
  src/procedure/nodes/collect2d.cpp
  src/procedure/nodes/collect3d.cpp
  src/procedure/nodes/fit1d.cpp
  src/procedure/nodes/fit1d.h
  src/procedure/nodes/node.cpp
  src/procedure/nodes/node.h
  src/procedure/nodes/process1d.cpp
  src/procedure/nodes/process2d.cpp
  src/procedure/nodes/process3d.cpp
  src/procedure/nodes/select.cpp
  src/procedure/nodes/sequence.cpp
  src/procedure/nodes/sequence.h
  src/procedure/procedure.cpp
  src/procedure/procedure.h
  unit/gui/procedure.cpp
Labels: 8

#1174 IntegerSpin with Limits
  src/gui/keywordwidgets/optionalint.hui
  src/gui/keywordwidgets/optionalint_funcs.cpp
  src/gui/widgets/CMakeLists.txt
  src/gui/widgets/integerspin.hui
  src/gui/widgets/integerspin_funcs.cpp
  src/modules/bragg/bragg.cpp
  src/modules/bragg/bragg.h
  src/modules/bragg/process.cpp
  src/modules/rdf/process.cpp
  src/modules/rdf/rdf.cpp
  src/modules/rdf/rdf.h
  src/modules/sq/process.cpp
  src/modules/sq/sq.cpp
  src/modules/sq/sq.h
Labels: 4

#1216 Patch August 22 - Part 1
  src/data/spacegroups.cpp
  src/data/spacegroups.h
  src/gui/keywordwidgets/function1d.h
  src/gui/keywordwidgets/function1d_funcs.cpp
  src/gui/render/renderablespecies.cpp
  src/main/simulation.cpp
Labels: 4

#1218 1215 Instantaneous CN
  src/keywords/base.h
  src/modules/calculate_cn/cn.cpp
  src/modules/calculate_cn/cn.h
  src/modules/calculate_cn/process.cpp
  src/procedure/nodes/process1d.cpp
  src/procedure/nodes/process1d.h
  src/procedure/nodes/sum1d.cpp
  src/procedure/nodes/sum1d.h
  web/content/docs/modules/analysis/calculatecn/_index.md
  web/content/docs/procedures/nodes/process1dnode.md
  web/content/docs/procedures/nodes/sum1dnode.md
Labels: 4

#1220 985 Disallow Tab Renaming
  src/gui/maintabswidget.hui
  src/gui/maintabswidget_funcs.cpp
Labels: 1

#1193 OptionalIntegerkeyword Unit Test
  unit/gui/CMakeLists.txt
  unit/gui/optionalIntegerKeyword.cpp
  unit/keywords/CMakeLists.txt
  unit/keywords/optionalInteger.cpp
Labels: 1

#1222 Move CN calculation to RDF (Procedure Editing Bonus Work)
  src/modules/calculate_cn/CMakeLists.txt
  src/modules/calculate_cn/cn.cpp
  src/modules/calculate_cn/cn.h
  src/modules/calculate_cn/functions.cpp
  src/modules/calculate_cn/gui/CMakeLists.txt
  src/modules/calculate_cn/gui/calculatecnwidget.h
  src/modules/calculate_cn/gui/calculatecnwidget.ui
  src/modules/calculate_cn/gui/calculatecnwidget_funcs.cpp
  src/modules/calculate_cn/process.cpp
  src/modules/calculate_rdf/functions.cpp
  src/modules/calculate_rdf/gui/calculaterdfwidget.ui
  src/modules/calculate_rdf/gui/calculaterdfwidget_funcs.cpp
  src/modules/calculate_rdf/process.cpp
  src/modules/calculate_rdf/rdf.cpp
  src/modules/calculate_rdf/rdf.h
  src/modules/registry.cpp
  src/modules/widgetproducer.cpp
  src/procedure/nodes/sum1d.cpp
  src/procedure/nodes/sum1d.h
  tests/calculate_cn/CMakeLists.txt
  tests/calculate_cn/README
  tests/calculate_rdf/CMakeLists.txt
  tests/calculate_rdf/cn.txt
Labels: 2

#1231 SCARF Scripts
  scripts/README.md
  scripts/scarf-add-module
  scripts/scarf-add-module.modulefile
  scripts/scarf-add-module.runscript
  web/content/docs/run/scarf.md
Labels: 2

#1232 1228 Tab Signalling
  src/gui/maintabswidget.hui
  src/gui/maintabswidget_funcs.cpp
Labels: 1

#1234 Unknown Module Types
  examples/emim-oac/input.txt
  examples/water/input.txt
  src/main/keywords_layer.cpp
Labels: 1

#1224 Procedure Editing - Part 4
  src/gui/charts/procedure.cpp
  src/gui/charts/procedure.h
  src/gui/models/expressionVariableVectorModel.cpp
  src/gui/models/procedureModel.cpp
  src/keywords/expressionvariablevector.cpp
  src/keywords/node.cpp
  src/keywords/nodeandinteger.cpp
  src/keywords/nodebranch.cpp
  src/keywords/nodebranch.h
  src/keywords/nodeunderlay.cpp
  src/keywords/nodevalue.cpp
  src/keywords/nodevalue.h
  src/keywords/nodevalueenumoptions.h
  src/keywords/nodevector.cpp
  src/keywords/nodevector.h
  src/keywords/store.cpp
  src/keywords/store.h
  src/keywords/vec3nodevalue.cpp
  src/modules/calculate_angle/angle.cpp
  src/modules/calculate_axisangle/axisangle.cpp
  src/modules/calculate_dangle/dangle.cpp
  src/modules/calculate_rdf/rdf.cpp
  src/modules/calculate_sdf/sdf.cpp
  src/procedure/nodes/CMakeLists.txt
  src/procedure/nodes/collect1d.cpp
  src/procedure/nodes/collect1d.h
  src/procedure/nodes/collect2d.cpp
  src/procedure/nodes/collect2d.h
  src/procedure/nodes/collect3d.cpp
  src/procedure/nodes/collect3d.h
  src/procedure/nodes/copy.h
  src/procedure/nodes/fit1d.cpp
  src/procedure/nodes/fit1d.h
  src/procedure/nodes/node.cpp
  src/procedure/nodes/node.h
  src/procedure/nodes/nodes.h
  src/procedure/nodes/process1d.cpp
  src/procedure/nodes/process1d.h
  src/procedure/nodes/process2d.cpp
  src/procedure/nodes/process2d.h
  src/procedure/nodes/process3d.cpp
  src/procedure/nodes/process3d.h
  src/procedure/nodes/registry.cpp
  src/procedure/nodes/select.cpp
  src/procedure/nodes/select.h
  src/procedure/nodes/sequence.cpp
  src/procedure/nodes/sequence.h
  src/procedure/procedure.cpp
  src/procedure/procedure.h
  unit/classes/CMakeLists.txt
  unit/classes/procedure.cpp
  unit/gui/procedure.cpp
Labels: 8
