Repository disorderedmaterials/dissolve, pull requests merged in 2022-01, with the labels that each got.

#918 Filter Partials
  src/gui/icons/general_cross.svg
  src/modules/neutronsq/gui/neutronsqwidget.h
  src/modules/neutronsq/gui/neutronsqwidget.ui
  src/modules/neutronsq/gui/neutronsqwidget_funcs.cpp
  src/modules/rdf/gui/rdfwidget.h
  src/modules/rdf/gui/rdfwidget.ui
  src/modules/rdf/gui/rdfwidget_funcs.cpp
  src/modules/sq/gui/sqwidget.h
  src/modules/sq/gui/sqwidget.ui
  src/modules/sq/gui/sqwidget_funcs.cpp
  src/modules/xraysq/gui/xraysqwidget.h
  src/modules/xraysq/gui/xraysqwidget.ui
  src/modules/xraysq/gui/xraysqwidget_funcs.cpp
Labels: 2

#924 Parameter Naming
  src/base/enumoptions.h
  src/base/sysfunc.cpp
  src/base/sysfunc.h
  src/classes/species.cpp
  src/classes/species_ff.cpp
  src/classes/species_io.cpp
  src/classes/speciesangle.cpp
  src/classes/speciesangle.h
  src/classes/speciesbond.cpp
  src/classes/speciesbond.h
  src/classes/speciesimproper.cpp
  src/classes/speciesimproper.h
  src/classes/speciesintra.h
  src/classes/speciestorsion.cpp
  src/classes/speciestorsion.h
  src/data/ff/uff/uff.cpp
  src/gui/models/masterTermModel.cpp
  src/gui/models/speciesAngleModel.cpp
  src/gui/models/speciesBondModel.cpp
  src/gui/models/speciesImproperModel.cpp
  src/gui/models/speciesModelUtils.h
  src/gui/models/speciesTorsionModel.cpp
  src/main/io.cpp
  src/main/keywords_master.cpp
  src/templates/algorithms.h
  tests/inputs/benzene.txt
  tests/inputs/py5-ntf2.txt
  tests/inputs/water.txt
  unit/algorithms/CMakeLists.txt
  unit/algorithms/sysFunc.cpp
  unit/gui/datamanager.cpp
  unit/gui/forcefieldTab.cpp
  unit/gui/isotopologeSetModel.cpp
  unit/gui/masterTerms.cpp
  unit/gui/speciestab.cpp
  unit/io/CMakeLists.txt
  unit/io/intraParameterParse.cpp
  unit/math/derivatives.cpp
  unit/math/geometryMin.cpp
Labels: 8

#926 Autodetect relevant charge source
  src/classes/configuration.h
  src/classes/configuration_contents.cpp
  src/classes/pairpotential.cpp
  src/classes/pairpotential.h
  src/classes/potentialmap.cpp
  src/gui/forcefieldtab.h
  src/gui/forcefieldtab.ui
  src/gui/forcefieldtab_funcs.cpp
  src/gui/gui.h
  src/gui/gui.ui
  src/gui/menu_simulation.cpp
  src/gui/speciestab_geometry.cpp
  src/main.cpp
  src/main/dissolve.cpp
  src/main/dissolve.h
  src/main/io.cpp
  src/main/keywords.h
  src/main/keywords_pairpotentials.cpp
  src/main/pairpotentials.cpp
  src/main/simulation.cpp
  src/modules/checkspecies/process.cpp
  src/modules/md/process.cpp
  tests/broadening/argon_dep0.1indep0.2.txt
  tests/broadening/argon_dep0.2indep0.1.txt
  tests/broadening/argon_qdep0.1.txt
  tests/broadening/argon_qdep0.2.txt
  tests/broadening/argon_qindep0.1.txt
  tests/broadening/argon_qindep0.2.txt
  tests/calculate_avgmol/bendy.txt
  tests/energyforce1/water3000-coul.txt
  tests/energyforce1/water3000-elec.txt
  tests/energyforce1/water3000-full.txt
  tests/energyforce1/water3000-intra.txt
  tests/energyforce1/water3000-vdw.txt
  tests/energyforce2/torsions.txt
  tests/energyforce3/poe.txt
  tests/energyforce3/py4oh-ntf2.txt
  tests/energyforce3/py5-ntf2.txt
  tests/energyforce4/py4oh-ntf2.txt
  tests/energyforce4/py5-ntf2.txt
  tests/ff/oplsaa2005-aromatics.txt
  tests/ff/pcl2019-anions.txt
  tests/ff/uff-nmethylformamide.txt
  tests/ff/uff4mof-mof5.txt
  tests/md/10.forces
  tests/md/8.restart
  tests/md/9.restart
  tests/md/CMakeLists.txt
  tests/md/README
  tests/md/benzene.txt
  tests/md/reference.restart
  tests/rdfmethod/cells.txt
  tests/rdfmethod/simple.txt
  unit/classes/cells.cpp
  web/content/docs/inputfile/pairpotentialsblock.md
Labels: 4

#927 GUI Awareness
  src/base/messenger.cpp
  src/base/messenger.h
  src/dissolve-gui.cpp
  src/gui/gui.h
  src/gui/gui.ui
  src/gui/gui_funcs.cpp
  src/gui/gui_simulation.cpp
  src/gui/icons/control_play.svg
  src/gui/icons/control_stop.svg
  src/gui/layertab_funcs.cpp
  src/gui/main.qrc
  src/gui/menu_file.cpp
  src/gui/menu_simulation.cpp
  src/main.cpp
  src/main/cli.cpp
  src/main/cli.h
  src/main/dissolve.h
  src/main/io.cpp
  src/main/simulation.cpp
  web/content/docs/developers/architecture.md
  web/content/docs/outputfiles/heartbeat.md
  web/content/docs/run/cli.md
  web/content/docs/run/workflow.md
Labels: 4

#934 Package Naming
  .azure-pipelines/templates/build-linux.yml
  .azure-pipelines/templates/create-release.yml
Labels: 1

#939 Keyword Signals Update
  src/gui/keywordwidgets/atomtypevector_funcs.cpp
  src/gui/keywordwidgets/bool_funcs.cpp
  src/gui/keywordwidgets/configuration_funcs.cpp
  src/gui/keywordwidgets/configurationvector_funcs.cpp
  src/gui/keywordwidgets/double_funcs.cpp
  src/gui/keywordwidgets/enumoptions_funcs.cpp
  src/gui/keywordwidgets/expressionvariablevector_funcs.cpp
  src/gui/keywordwidgets/fileandformat_funcs.cpp
  src/gui/keywordwidgets/function1d_funcs.cpp
  src/gui/keywordwidgets/integer_funcs.cpp
  src/gui/keywordwidgets/isotopologueset_funcs.cpp
  src/gui/keywordwidgets/module_funcs.cpp
  src/gui/keywordwidgets/modulevector_funcs.cpp
  src/gui/keywordwidgets/node_funcs.cpp
  src/gui/keywordwidgets/nodeandinteger_funcs.cpp
  src/gui/keywordwidgets/nodevalue_funcs.cpp
  src/gui/keywordwidgets/nodevalueenumoptions_funcs.cpp
  src/gui/keywordwidgets/nodevector_funcs.cpp
  src/gui/keywordwidgets/optionaldouble_funcs.cpp
  src/gui/keywordwidgets/optionalint_funcs.cpp
  src/gui/keywordwidgets/range_funcs.cpp
  src/gui/keywordwidgets/species_funcs.cpp
  src/gui/keywordwidgets/speciessite_funcs.cpp
  src/gui/keywordwidgets/speciessitevector_funcs.cpp
  src/gui/keywordwidgets/speciesvector_funcs.cpp
  src/gui/keywordwidgets/stdstring_funcs.cpp
  src/gui/keywordwidgets/vec3double_funcs.cpp
  src/gui/keywordwidgets/vec3integer_funcs.cpp
  src/gui/keywordwidgets/vec3nodevalue_funcs.cpp
  src/gui/modulecontrolwidget_funcs.cpp
  src/keywords/base.cpp
  src/keywords/base.h
  src/keywords/signals.cpp
  src/keywords/signals.h
  src/modules/calculate_avgmol/avgmol.cpp
  src/modules/neutronsq/neutronsq.cpp
  src/modules/neutronsq/process.cpp
  src/modules/xraysq/process.cpp
  src/modules/xraysq/xraysq.cpp
  unit/classes/CMakeLists.txt
  unit/classes/keywordsignals.cpp
Labels: 2

#935 Patch 01/2022
  examples/argon/input.txt
  examples/benzene/input.txt
  examples/silica_bulk/input.txt
  examples/water/input.txt
  src/classes/scaledenergykernel.cpp
  src/classes/scaledenergykernel.h
  src/data/ff/pcl2019/base.cpp
  src/dissolve-gui.cpp
  src/gui/CMakeLists.txt
  src/gui/addforcefieldtermsdialog_funcs.cpp
  src/gui/delegates/CMakeLists.txt
  src/gui/delegates/intraformcombo.h
  src/gui/delegates/isotopecombo.hui
  src/gui/delegates/isotopecombo_funcs.cpp
  src/gui/forcefieldtab.h
  src/gui/forcefieldtab.ui
  src/gui/forcefieldtab_funcs.cpp
  src/gui/gui.h
  src/gui/gui.ui
  src/gui/gui_funcs.cpp
  src/gui/gui_io.cpp
  src/gui/keywordwidgets/CMakeLists.txt
  src/gui/keywordwidgets/producers.cpp
  src/gui/keywordwidgets/species.h
  src/gui/keywordwidgets/species.ui
  src/gui/keywordwidgets/species_funcs.cpp
  src/gui/menu_file.cpp
  src/gui/menu_layer.cpp
  src/gui/modulecontrolwidget_funcs.cpp
  src/gui/speciestab_funcs.cpp
  src/gui/widgets/CMakeLists.txt
  src/io/import/data1d.cpp
  src/main.cpp
  src/main/cli.cpp
  src/main/cli.h
  src/main/dissolve.h
  src/main/layers.cpp
  src/main/pairpotentials.cpp
  src/main/simulation.cpp
  src/math/filters.cpp
  src/module/layer.cpp
  src/modules/calculate_angle/angle.h
  src/modules/calculate_angle/process.cpp
  src/modules/calculate_axisangle/axisangle.h
  src/modules/calculate_axisangle/process.cpp
  src/modules/calculate_dangle/dangle.h
  src/modules/calculate_dangle/process.cpp
  src/modules/calculate_rdf/process.cpp
  src/modules/calculate_rdf/rdf.h
  src/modules/epsr/process.cpp
  src/modules/forces/process.cpp
  src/modules/neutronsq/functions.cpp
  src/modules/neutronsq/process.cpp
  src/modules/rdf/functions.cpp
  src/modules/xraysq/process.cpp
  src/templates/tbb-defs.h
  src/templates/tbb-fallbacks.h
  src/templates/vector3.h
  unit/classes/cells.cpp
Labels: 4

#950 Remove RefList
  src/classes/atom.h
  src/classes/cellarray.cpp
  src/classes/changedata.cpp
  src/classes/distributor.cpp
  src/classes/speciesatom.h
  src/classes/speciessite.h
  src/gui/charts/chart.hui
  src/gui/charts/procedure.cpp
  src/gui/charts/procedure.h
  src/gui/charts/procedurenode.h
  src/gui/charts/procedurenode_funcs.cpp
  src/gui/dataviewer_contextmenu.cpp
  src/gui/datawidget_funcs.cpp
  src/gui/gettabnamedialog.h
  src/gui/gizmo.cpp
  src/gui/gizmo.h
  src/gui/helpers/comboboxcontroller.h
  src/gui/helpers/comboboxupdater.h
  src/gui/helpers/listwidgetupdater.h
  src/gui/helpers/tablewidgetupdater.h
  src/gui/helpers/treewidgetupdater.h
  src/gui/maintab.h
  src/gui/render/colourscaledelta.h
  src/gui/render/colourscalepoint.h
  src/gui/render/renderable.cpp
  src/gui/render/renderable.h
  src/gui/selectconfigurationwidget_funcs.cpp
  src/gui/viewer.hui
  src/gui/viewer_view.cpp
  src/keywords/dynamicsitenodes.cpp
  src/module/group.cpp
  src/module/group.h
  src/module/groups.cpp
  src/module/groups.h
  src/module/module.h
  src/modules/rdf/functions.cpp
  src/procedure/nodes/dynamicsite.h
  src/procedure/nodes/fit1d.h
  src/procedure/nodes/select.cpp
  src/procedure/nodes/select.h
  src/procedure/nodes/sum1d.h
  src/templates/reflist.h
Labels: 4

#959 Patch 01 2022 2
  src/classes/species.h
  src/classes/species_intra.cpp
  src/gui/forcefieldtab.h
  src/gui/forcefieldtab_funcs.cpp
  src/gui/gui_funcs.cpp
  src/gui/importcifdialog.h
  src/gui/importcifdialog.ui
  src/gui/importcifdialog_funcs.cpp
  src/gui/keywordwidgets/isotopologueset_funcs.cpp
  src/gui/layertab.h
  src/gui/layertab_funcs.cpp
  src/gui/models/isotopologueSetModel.cpp
  src/gui/models/isotopologueSetModel.h
  src/gui/models/moduleLayerModel.cpp
  src/gui/models/moduleLayerModel.h
  src/gui/speciestab.ui
  src/main/keywords_module.cpp
  src/modules/calculate_cn/cn.cpp
  src/modules/neutronsq/process.cpp
  src/modules/rdf/gui/rdfwidget_funcs.cpp
  src/modules/xraysq/process.cpp
  tests/epsr/water-poisson.txt
Labels: 4
