Repository disorderedmaterials/dissolve, pull requests merged in 2023-10, with the labels that each got.

#1673 Fix for segmentation fault crash in import trajectory module
  src/io/import/trajectory.cpp
Labels: Type: Bug, 4

#1676 Free up memory in GitHub runner
  .github/workflows/build/linux/action.yml
Labels: Scope: CI

#1678 Beginning TOML Testing
  tests/io/CMakeLists.txt
  tests/modules/histogramCN.cpp
  tests/modules/orientedSDF.cpp
  tests/testData.h
Labels: TOML

#1680 Fix import of node name when deserialising
  src/procedure/nodes/node.cpp
  tests/modules/histogramCN.cpp
  tests/modules/orientedSDF.cpp
Labels: TOML
