Repository disorderedmaterials/dissolve, pull requests merged in 2023-11, with the labels that each got.

#1682 Correctness testing with TOML
  src/classes/serializablePairPotential.cpp
  src/classes/serializablePairPotential.h
  src/main/dissolve.cpp
  src/main/io.cpp
  tests/modules/epsr.cpp
  tests/modules/siteRDF.cpp
  tests/testData.h
Labels: TOML

#1701 Fix serialisation of Species Site with TOML
  src/classes/speciesSite.cpp
  tests/modules/siteRDF.cpp
Labels: 16, TOML

#1711 Add EnumOption for SpeciesSite::SiteType
  src/classes/speciesSite.cpp
  src/classes/speciesSite.h
Labels: TOML

#1697 Change to CMakeLists.txt to allow for arm64 builds
  CMakeLists.txt
Labels: Only: OSX

#1719 1704 remove serializable pair potential
  src/classes/CMakeLists.txt
  src/classes/pairPotential.h
  src/classes/serializablePairPotential.cpp
  src/classes/serializablePairPotential.h
  src/main/dissolve.cpp
  src/main/dissolve.h
  src/main/io.cpp
Labels: 2, TOML

#1715 1614 explicit toml context
  src/base/serialiser.h
  src/templates/vector3.h
Labels: 16, TOML

#1729 Rework TOML backend
  src/base/serialiser.h
  src/classes/atomType.cpp
  src/classes/box.cpp
  src/classes/coreData.cpp
  src/classes/isotopologue.cpp
  src/classes/species.cpp
  src/classes/valueStore.cpp
  src/keywords/dataSource.h
  src/main/io.cpp
  src/module/layer.cpp
  src/module/module.cpp
  src/templates/orderedMap.h
  src/templates/vector3.h
  tests/algorithms/CMakeLists.txt
  tests/algorithms/orderedMap.cpp
Labels: 16, TOML
